import { tasksRoutes } from "./tasks.routes.js";
import { tasksPublicApiRoutes } from "./public-api.routes.js";

const tasksModule = {
  id: "tasks",
  name: "Tasks",
  displayName: "Tasks",
  description: "Workspace, client, and project task tracking with scoped assignment and due-date foundations.",
  category: "core-workflow",
  version: "0.31.16",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [tasksRoutes],
  publicApiRoutes: [tasksPublicApiRoutes],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: null,
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    { label: "Tasks", href: "tasks.html", parent: "projects.html", counts: ["overdue", "dueSoon"] },
  ],
  protectedViews: [
    {
      id: "tasks",
      path: "/tasks.html",
      moduleId: "tasks",
      file: "tasks.html",
      requiredPermissions: ["tasks.view"],
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
      allowDisabledRead: true,
    },
    {
      id: "tasks-settings",
      path: "/tasks-settings.html",
      moduleId: "tasks",
      file: "tasks-settings.html",
      requiredPermissions: ["workspace_settings.manage"],
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "tasks-script",
      moduleId: "tasks",
      path: "/js/tasks.js",
      type: "script",
      views: ["tasks"],
      requiredPermissions: ["tasks.view"],
    },
    {
      id: "tasks-module-settings-script",
      moduleId: "tasks",
      path: "/js/module-settings.js",
      type: "script",
      views: ["tasks-settings"],
      requiredPermissions: ["workspace_settings.manage"],
    },
  ],
  dashboard: [
    {
      id: "task-summary",
      label: "Task Summary",
      renderer: "task-summary",
      counts: ["overdue", "dueSoon", "assignedToMe"],
      links: ["overdue", "dueSoon", "assignedToMe"],
    },
  ],
  workbench: [
    {
      id: "task-workbench-items",
      label: "Tasks",
      renderer: "task-workbench-items",
      moduleId: "tasks",
      requiredPermissions: ["tasks.view"],
      requiredWorkspaceCapabilities: ["tasks"],
      requiresEnabledModules: ["tasks"],
      defaultCollapsed: false,
      sortOrder: 20,
    },
  ],
  reporting: [],
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/tasks", scope: "tasks:read" },
    { method: "GET", path: "/api/v1/tasks/:taskId", scope: "tasks:read" },
    { method: "POST", path: "/api/v1/tasks", scope: "tasks:write" },
    { method: "PUT", path: "/api/v1/tasks/:taskId", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/complete", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/reopen", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/archive", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/restore", scope: "tasks:write" },
  ],
  requiredPermissions: [
    "tasks.create",
    "tasks.view",
    "tasks.edit_own",
    "tasks.edit_all",
    "tasks.assign",
    "tasks.complete",
    "tasks.archive",
    "tasks.restore",
  ],
  permissions: [
    {
      id: "tasks.create",
      moduleId: "tasks",
      label: "Create Tasks",
      description: "Create tasks in an authorized workspace, client, or project scope.",
      resource: "tasks",
      operation: "create",
    },
    {
      id: "tasks.view",
      moduleId: "tasks",
      label: "View Tasks",
      description: "View tasks in an authorized workspace, client, or project scope.",
      resource: "tasks",
      operation: "read",
    },
    {
      id: "tasks.edit_own",
      moduleId: "tasks",
      label: "Edit Own Tasks",
      description: "Edit tasks created by or assigned to the actor in scope.",
      resource: "tasks",
      operation: "update",
    },
    {
      id: "tasks.edit_all",
      moduleId: "tasks",
      label: "Edit All Tasks",
      description: "Edit all tasks in an authorized workspace, client, or project scope.",
      resource: "tasks",
      operation: "update",
    },
    {
      id: "tasks.assign",
      moduleId: "tasks",
      label: "Assign Tasks",
      description: "Assign tasks to eligible workspace users.",
      resource: "tasks",
      operation: "assign",
    },
    {
      id: "tasks.complete",
      moduleId: "tasks",
      label: "Complete Tasks",
      description: "Complete and reopen authorized tasks.",
      resource: "tasks",
      operation: "update",
    },
    {
      id: "tasks.archive",
      moduleId: "tasks",
      label: "Archive Tasks",
      description: "Archive authorized tasks.",
      resource: "tasks",
      operation: "archive",
    },
    {
      id: "tasks.restore",
      moduleId: "tasks",
      label: "Restore Tasks",
      description: "Restore archived tasks.",
      resource: "tasks",
      operation: "restore",
    },
  ],
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "workspace_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "client_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "project_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "client_user", permissions: ["tasks.create", "tasks.view", "tasks.edit_own", "tasks.complete"] },
    { roleId: "project_user", permissions: ["tasks.create", "tasks.view", "tasks.edit_own", "tasks.complete"] },
    { roleId: "client_external_user", permissions: ["tasks.view"] },
  ],
  resourceDefinitions: [
    {
      key: "tasks",
      moduleId: "tasks",
      label: "Tasks",
      operations: ["read", "create", "update", "delete", "archive", "restore", "assign", "manage"],
    },
  ],
  apiScopes: [
    {
      id: "tasks:read",
      moduleId: "tasks",
      label: "Read Tasks",
      description: "Read tasks through the public API.",
      access: "read",
    },
    {
      id: "tasks:write",
      moduleId: "tasks",
      label: "Write Tasks",
      description: "Create and update tasks through the public API.",
      access: "write",
    },
  ],
  timerSources: [
    {
      sourceType: "task",
      moduleId: "tasks",
      label: "Task Timer",
      listRoute: "/api/tasks/timers",
      startRoute: "/api/tasks/:taskId/timer",
      pauseRoute: "/api/tasks/:taskId/timer",
      finalizeRoute: "/api/tasks/:taskId/timer/finalize",
      requiredPermissions: ["tasks.view", "time_entries.create"],
      requiredModules: ["tasks", "time-tracking"],
    },
  ],
  workItemSources: [
    {
      sourceType: "task",
      moduleId: "tasks",
      label: "Tasks",
      listRoute: "/api/workbench/bootstrap",
      requiredPermissions: ["tasks.view"],
      requiredModules: ["tasks"],
      filterHints: {
        supported: ["all", "due-soon", "assigned-to-me", "active"],
      },
      sortHints: {
        supported: ["due_at", "priority", "title", "timer_status"],
      },
    },
  ],
  workspaceCapabilityRequirements: ["projects", "clients_projects"],
  settings: [
    {
      id: "tasksEnabled",
      label: "Tasks",
      type: "boolean",
      moduleStatus: true,
    },
    {
      id: "taskTimersEnabled",
      label: "Task Timers",
      type: "boolean",
      moduleStatus: false,
    },
  ],
  frameworkDependencies: [
    "audit-service",
    "client-projects",
    "module-access",
    "permissions-service",
    "timezone-normalization",
    "workspace-settings",
  ],
};

export { tasksModule };
