import { tasksRoutes } from "./tasks.routes.js";
import { tasksPublicApiRoutes } from "./public-api.routes.js";

const tasksModule = {
  id: "tasks",
  name: "Tasks",
  displayName: "Tasks",
  description: "Workspace, client, and project task tracking with scoped assignment and due-date foundations.",
  terminology: {
    default: {
      label: "Tasks",
      singular: "Task",
      plural: "Tasks",
      navigationLabel: "Tasks",
      createButton: "Create Task",
      emptyState: "No tasks found.",
    },
  },
  category: "core-workflow",
  version: "0.32.3",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [tasksRoutes],
  publicApiRoutes: [tasksPublicApiRoutes],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: null,
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    { label: "Tasks", href: "tasks.html", parent: "projects.html", counts: ["overdue", "dueSoon"] },
  ],
  protectedViews: [
    {
      id: "tasks",
      path: "/tasks.html",
      moduleId: "tasks",
      file: "tasks.html",
      requiredPermissions: ["tasks.view"],
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
      allowDisabledRead: true,
    },
    {
      id: "tasks-settings",
      path: "/tasks-settings.html",
      moduleId: "tasks",
      file: "tasks-settings.html",
      requiredPermissions: ["workspace_settings.manage"],
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "tasks-script",
      moduleId: "tasks",
      path: "/js/tasks.js",
      type: "script",
      views: ["tasks"],
      requiredPermissions: ["tasks.view"],
    },
    {
      id: "tasks-module-settings-script",
      moduleId: "tasks",
      path: "/js/module-settings.js",
      type: "script",
      views: ["tasks-settings"],
      requiredPermissions: ["workspace_settings.manage"],
    },
  ],
  dashboard: [
    {
      id: "task-summary",
      label: "Task Summary",
      renderer: "task-summary",
      counts: ["overdue", "dueSoon", "assignedToMe"],
      links: ["overdue", "dueSoon", "assignedToMe"],
    },
  ],
  workbench: [
    {
      id: "task-workbench-items",
      label: "Tasks",
      renderer: "task-workbench-items",
      moduleId: "tasks",
      requiredPermissions: ["tasks.view"],
      requiredWorkspaceCapabilities: ["tasks"],
      requiresEnabledModules: ["tasks"],
      defaultCollapsed: false,
      sortOrder: 20,
    },
  ],
  reporting: [],
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/tasks", scope: "tasks:read" },
    { method: "GET", path: "/api/v1/tasks/:taskId", scope: "tasks:read" },
    { method: "POST", path: "/api/v1/tasks", scope: "tasks:write" },
    { method: "PUT", path: "/api/v1/tasks/:taskId", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/complete", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/reopen", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/archive", scope: "tasks:write" },
    { method: "POST", path: "/api/v1/tasks/:taskId/restore", scope: "tasks:write" },
  ],
  requiredPermissions: [
    "tasks.create",
    "tasks.view",
    "tasks.edit_own",
    "tasks.edit_all",
    "tasks.assign",
    "tasks.complete",
    "tasks.archive",
    "tasks.restore",
  ],
  permissions: [
    {
      id: "tasks.create",
      moduleId: "tasks",
      label: "Create Tasks",
      description: "Create tasks in an authorized workspace, client, or project scope.",
      resource: "tasks",
      operation: "create",
    },
    {
      id: "tasks.view",
      moduleId: "tasks",
      label: "View Tasks",
      description: "View tasks in an authorized workspace, client, or project scope.",
      resource: "tasks",
      operation: "read",
    },
    {
      id: "tasks.edit_own",
      moduleId: "tasks",
      label: "Edit Own Tasks",
      description: "Edit tasks created by or assigned to the actor in scope.",
      resource: "tasks",
      operation: "update",
    },
    {
      id: "tasks.edit_all",
      moduleId: "tasks",
      label: "Edit All Tasks",
      description: "Edit all tasks in an authorized workspace, client, or project scope.",
      resource: "tasks",
      operation: "update",
    },
    {
      id: "tasks.assign",
      moduleId: "tasks",
      label: "Assign Tasks",
      description: "Assign tasks to eligible workspace users.",
      resource: "tasks",
      operation: "assign",
    },
    {
      id: "tasks.complete",
      moduleId: "tasks",
      label: "Complete Tasks",
      description: "Complete and reopen authorized tasks.",
      resource: "tasks",
      operation: "update",
    },
    {
      id: "tasks.archive",
      moduleId: "tasks",
      label: "Archive Tasks",
      description: "Archive authorized tasks.",
      resource: "tasks",
      operation: "archive",
    },
    {
      id: "tasks.restore",
      moduleId: "tasks",
      label: "Restore Tasks",
      description: "Restore archived tasks.",
      resource: "tasks",
      operation: "restore",
    },
  ],
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "workspace_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "client_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "project_admin", permissions: ["tasks.create", "tasks.view", "tasks.edit_all", "tasks.assign", "tasks.complete", "tasks.archive", "tasks.restore"] },
    { roleId: "client_user", permissions: ["tasks.create", "tasks.view", "tasks.edit_own", "tasks.complete"] },
    { roleId: "project_user", permissions: ["tasks.create", "tasks.view", "tasks.edit_own", "tasks.complete"] },
    { roleId: "client_external_user", permissions: ["tasks.view"] },
  ],
  resourceDefinitions: [
    {
      key: "tasks",
      moduleId: "tasks",
      label: "Tasks",
      operations: ["read", "create", "update", "delete", "archive", "restore", "assign", "manage"],
    },
  ],
  auditRecordTypes: [
    {
      recordType: "task",
      moduleId: "tasks",
      label: "Task",
      description: "Task records and task lifecycle audit history.",
    },
    {
      recordType: "task_recurrence_template",
      moduleId: "tasks",
      label: "Task Recurrence Template",
      description: "Recurring task series templates and recurrence audit history.",
    },
  ],
  taggableTypes: [
    {
      targetType: "task",
      moduleId: "tasks",
      label: "Task",
      description: "Task records that can receive workspace tags.",
      idField: "task_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: "tasks.view",
      requiredTagPermission: "tags.assign",
      requiredModules: ["tasks"],
    },
  ],
  apiScopes: [
    {
      id: "tasks:read",
      moduleId: "tasks",
      label: "Read Tasks",
      description: "Read tasks through the public API.",
      access: "read",
    },
    {
      id: "tasks:write",
      moduleId: "tasks",
      label: "Write Tasks",
      description: "Create and update tasks through the public API.",
      access: "write",
    },
  ],
  eventTypes: [
    {
      event: "task.created",
      moduleId: "tasks",
      label: "Task Created",
      description: "Emitted after a task is created.",
      recordType: "task",
    },
    {
      event: "task.updated",
      moduleId: "tasks",
      label: "Task Updated",
      description: "Emitted after a task is updated or reopened.",
      recordType: "task",
    },
    {
      event: "task.assigned",
      moduleId: "tasks",
      label: "Task Assigned",
      description: "Emitted after task assignees change.",
      recordType: "task",
    },
    {
      event: "task.completed",
      moduleId: "tasks",
      label: "Task Completed",
      description: "Emitted after a task is completed.",
      recordType: "task",
    },
    {
      event: "task.archived",
      moduleId: "tasks",
      label: "Task Archived",
      description: "Emitted after a task is archived.",
      recordType: "task",
    },
    {
      event: "task.restored",
      moduleId: "tasks",
      label: "Task Restored",
      description: "Emitted after a task is restored from the archive.",
      recordType: "task",
    },
    {
      event: "task.due_soon",
      moduleId: "tasks",
      label: "Task Due Soon",
      description: "Reserved notification event for future task due-soon checks.",
      recordType: "task",
    },
    {
      event: "task.overdue",
      moduleId: "tasks",
      label: "Task Overdue",
      description: "Reserved notification event for future task overdue checks.",
      recordType: "task",
    },
  ],
  eventSummaries: [
    {
      event: "task.created",
      moduleId: "tasks",
      activity: {
        label: "Task Created",
        summary: ({ event }) => `Created task "${event.new_value?.title || event.record_id || "Task"}".`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: "Task Created",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" was created.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.updated",
      moduleId: "tasks",
      activity: {
        label: "Task Updated",
        summary: ({ event }) => `Updated task "${event.new_value?.title || event.record_id || "Task"}".`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: "Task Updated",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" was updated.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.assigned",
      moduleId: "tasks",
      activity: {
        label: "Task Assigned",
        summary: ({ event }) => `Updated assignees for task "${event.new_value?.title || event.record_id || "Task"}".`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: "Task Assigned",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" was assigned.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.completed",
      moduleId: "tasks",
      activity: {
        label: "Task Completed",
        summary: ({ event }) => `Completed task "${event.new_value?.title || event.record_id || "Task"}".`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: "Task Completed",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" was completed.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.archived",
      moduleId: "tasks",
      activity: {
        label: "Task Archived",
        summary: ({ event }) => `Archived task "${event.new_value?.title || event.record_id || "Task"}".`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: "Task Archived",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" was archived.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.restored",
      moduleId: "tasks",
      activity: {
        label: "Task Restored",
        summary: ({ event }) => `Restored task "${event.new_value?.title || event.record_id || "Task"}".`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: "Task Restored",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" was restored.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.due_soon",
      moduleId: "tasks",
      notification: {
        title: "Task Due Soon",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" is due soon.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
    {
      event: "task.overdue",
      moduleId: "tasks",
      notification: {
        title: "Task Overdue",
        body: ({ event }) => `Task "${event.new_value?.title || event.record_id || "Task"}" is overdue.`,
        url: ({ event }) => `tasks.html?task=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: ["assignees"],
      },
    },
  ],
  notificationEvents: [
    {
      id: "task.created",
      moduleId: "tasks",
      label: "Task Created",
      description: "Notifies task assignees when a task is created.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "assignees",
    },
    {
      id: "task.updated",
      moduleId: "tasks",
      label: "Task Updated",
      description: "Notifies task assignees when a task is updated.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "assignees",
    },
    {
      id: "task.assigned",
      moduleId: "tasks",
      label: "Task Assigned",
      description: "Notifies task assignees when assignees change.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "assignees",
    },
    {
      id: "task.completed",
      moduleId: "tasks",
      label: "Task Completed",
      description: "Notifies task assignees when a task is completed.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "assignees",
    },
    {
      id: "task.archived",
      moduleId: "tasks",
      label: "Task Archived",
      description: "Notifies task assignees when a task is archived.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "assignees",
    },
    {
      id: "task.restored",
      moduleId: "tasks",
      label: "Task Restored",
      description: "Notifies task assignees when a task is restored.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "assignees",
    },
    {
      id: "task.due_soon",
      moduleId: "tasks",
      label: "Task Due Soon",
      description: "Notifies task assignees when a task is due soon.",
      defaultEnabled: true,
      defaultPriority: "high",
      recipientMode: "assignees",
    },
    {
      id: "task.overdue",
      moduleId: "tasks",
      label: "Task Overdue",
      description: "Notifies task assignees when a task is overdue.",
      defaultEnabled: true,
      defaultPriority: "urgent",
      recipientMode: "assignees",
    },
  ],
  timerSources: [
    {
      sourceType: "task",
      moduleId: "tasks",
      label: "Task Timer",
      listRoute: "/api/tasks/timers",
      startRoute: "/api/tasks/:taskId/timer",
      pauseRoute: "/api/tasks/:taskId/timer",
      finalizeRoute: "/api/tasks/:taskId/timer/finalize",
      removeRoute: "/api/tasks/:taskId/timer",
      requiredPermissions: ["tasks.view", "time_entries.create"],
      requiredModules: ["tasks", "time-tracking"],
    },
  ],
  workItemSources: [
    {
      sourceType: "task",
      moduleId: "tasks",
      label: "Tasks",
      listRoute: "/api/tasks/workbench-items",
      requiredPermissions: ["tasks.view"],
      requiredModules: ["tasks"],
      filterHints: {
        supported: ["all", "due-soon", "assigned-to-me", "active"],
      },
      sortHints: {
        supported: ["due_at", "priority", "title", "timer_status"],
      },
    },
  ],
  workspaceCapabilityRequirements: ["projects", "clients_projects"],
  settings: [
    {
      id: "tasksEnabled",
      label: "Tasks",
      type: "boolean",
      moduleStatus: true,
    },
    {
      id: "taskTimersEnabled",
      label: "Task Timers",
      type: "boolean",
      moduleStatus: false,
    },
  ],
  frameworkDependencies: [
    "audit-service",
    "client-projects",
    "module-access",
    "permissions-service",
    "timezone-normalization",
    "workspace-settings",
  ],
};

export { tasksModule };
