import { randomUUID } from "node:crypto";
import { test, expect } from "./support/isolated-workspace.mjs";

test("Task rows retain hierarchy, parent handoff, checklist and real linked-note counts", async ({ isolatedWorkspace }, testInfo) => {
  const { page, api } = isolatedWorkspace;
  const suffix = randomUUID();
  const parentTitle = `Parent ${suffix}`, childTitle = `Child ${suffix}`;
  const parentReply = await api.post("/api/tasks", { data: { title: parentTitle } });
  expect(parentReply.status()).toBe(201);
  const parentId = (await parentReply.json()).task.task_id;
  const childReply = await api.post("/api/tasks", { data: { title: childTitle, next_action: "Review the remaining row" } });
  expect(childReply.status()).toBe(201);
  const childId = (await childReply.json()).task.task_id;
  const relationship = await api.post(`/api/tasks/${parentId}/children`, { data: { child_task_id: childId, is_blocking: true } });
  expect(relationship.status(), await relationship.text()).toBe(201);
  const checklist = await api.post(`/api/tasks/${childId}/checklist`, { data: { label: "Read the evidence" } });
  expect(checklist.status()).toBe(201);
  const note = await api.post("/api/notes", { data: { title: `Row note ${suffix}`, bodyMarkdown: "Row context" } });
  expect(note.status()).toBe(201);
  const noteId = (await note.json()).note.note_id;
  const link = await api.post(`/api/notes/${noteId}/links`, { data: { moduleId: "tasks", targetType: "task", targetId: childId } });
  expect(link.status(), await link.text()).toBe(201);

  await page.goto("/tasks.html");
  const rows = page.locator("tr.task-density-row");
  const parent = rows.filter({ has: page.getByText(parentTitle, { exact: true }) });
  const child = rows.filter({ has: page.getByText(childTitle, { exact: true }) });
  await expect(rows).toHaveCount(2);
  await expect(rows.first()).toContainText(parentTitle);
  await expect(rows.last()).toContainText(childTitle);
  await expect(parent).toHaveAttribute("data-task-nesting-depth", "0");
  await expect(child).toHaveAttribute("data-task-nesting-depth", "1");
  await expect(parent.locator(".task-context-summary")).toContainText("1 child");
  await expect(child.locator(".task-context-summary")).toContainText("0/1, next: Read the evidence");
  await expect(child.locator(".task-context-summary")).toContainText("Review the remaining row");
  await expect(child.locator(".task-note-count")).toHaveText("1 note");
  await expect(child.locator(".task-attachment-count")).toHaveCount(0);
  const parentChip = child.locator(".is-parent-link");
  await expect(parentChip).toHaveAttribute("title", `Open parent task: ${parentTitle}`);
  expect(await parentChip.evaluate((button) => button.nextElementSibling?.classList.contains("task-context-summary"))).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("task-rows.png"), fullPage: true });
  await parentChip.click();
  const dialog = page.locator("dialog[data-task-dialog][open]");
  await expect(dialog.locator("[data-task-title]")).toHaveValue(parentTitle);
  await dialog.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await child.locator(".task-note-count").click();
  await expect(dialog.locator("[data-task-title]")).toHaveValue(childTitle);
  await expect(dialog).toContainText(`Row note ${suffix}`);
});
