import { test, expect } from "./support/isolated-workspace.mjs";

test("Task Focus state carries checklist data through real timer mutations and related-context rendering", async ({ isolatedWorkspace }, testInfo) => {
  const { page, api } = isolatedWorkspace;
  const clientResponse = await api.post("/api/clients", { data: { name: "State Client" } });
  expect(clientResponse.status(), await clientResponse.text()).toBe(201);
  const clientId = (await clientResponse.json()).client.id;
  const projectResponse = await api.post(`/api/clients/${clientId}/projects`, { data: { name: "State Project" } });
  expect(projectResponse.status(), await projectResponse.text()).toBe(201);
  const projectId = (await projectResponse.json()).project.id;
  const taskResponse = await api.post("/api/tasks", { data: { title: "State preservation", client_id: clientId, project_id: projectId } });
  expect(taskResponse.status(), await taskResponse.text()).toBe(201);
  const taskId = (await taskResponse.json()).task.task_id;
  const itemResponse = await api.post(`/api/tasks/${taskId}/checklist`, { data: { label: "Keep this checklist row" } });
  expect(itemResponse.status(), await itemResponse.text()).toBe(201);
  const itemId = (await itemResponse.json()).item.task_checklist_item_id;
  /** @type {string[]} */ const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto(`/workbench.html?taskId=${taskId}`);
  await expect(page.locator("[data-workbench-task-focus-summary]")).toContainText("State preservation");
  const checklist = page.locator('[data-workbench-task-focus-checklist]');
  const checkbox = page.getByRole("checkbox", { name: "Mark Keep this checklist row complete" });
  // Use the module's own disclosure, rather than removing hidden/open state in the test.
  if (!await checkbox.isVisible()) await checklist.locator("summary").click();
  const checked = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith(`/checklist/${itemId}/check`));
  await checkbox.check(); expect((await checked).status()).toBe(200);
  await expect(checkbox).toBeChecked(); await expect(checkbox).toBeEnabled();
  await expect(checklist.locator("summary")).toContainText("1 / 1 complete");
  const timer = page.locator("[data-workbench-task-focus-timer]");
  const started = page.waitForResponse(response => response.request().method() === "PUT" && response.url().endsWith(`/api/tasks/${taskId}/timer`));
  await timer.getByRole("button", { name: "Start", exact: true }).click();
  expect((await started).status()).toBe(200);
  await expect(timer.locator("[data-workbench-task-focus-timer-status]")).toContainText("Running");
  await expect(checkbox).toBeChecked();
  await expect(checklist.locator("summary")).toContainText("1 / 1 complete");
  const paused = page.waitForResponse(response => response.request().method() === "PUT" && response.url().endsWith(`/api/tasks/${taskId}/timer`));
  await timer.getByRole("button", { name: "Pause", exact: true }).click();
  expect((await paused).status()).toBe(200);
  const capture = page.getByRole("dialog", { name: "Add resume note?" });
  await expect(capture).toBeVisible(); await capture.getByRole("button", { name: "No", exact: true }).click();
  await expect(timer.locator("[data-workbench-task-focus-timer-status]")).toContainText("Paused");
  await expect(checkbox).toBeChecked();
  if (testInfo.project.name === "mobile") await page.getByRole("button", { name: "Open Inspector", exact: true }).click();
  const inspector = page.locator("[data-workbench-inspector]");
  await expect(inspector).toBeVisible(); await expect(inspector.locator("h2")).toHaveText("Task context");
  await expect(inspector.locator("[data-workbench-inspector-list]")).toContainText("No related task context is available yet.");
  expect(errors).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath("focus-state.png"), fullPage: true });
});
