import {
  LIST_AUDIT_RECORD_TYPES,
  LIST_EVENT_TYPES,
  LIST_PERMISSIONS,
  LIST_RESOURCE_DEFINITION,
} from "./access-policy.js";
import { listsRoutes } from "./lists.routes.js";
import { listsPublicApiRoutes } from "./public-api.routes.js";
import { registerListsSearchIndexers } from "./search-indexers.js";
import { LIST_MODULE_ID } from "./storage-contract.js";
import { LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT } from "../../core/linked-context/provider-contract.js";

registerListsSearchIndexers();

const LIST_TYPE_LABELS = {
  bill_of_materials: "Bill of Materials",
  checklist: "Checklist",
  packing: "Packing",
  parts: "Parts",
  procurement: "Procurement",
  shopping: "Shopping",
  supplies: "Supplies",
};
const PURCHASE_STATUS_LABELS = {
  cancelled: "Cancelled",
  needed: "Needed",
  not_needed: "Not Needed",
  ordered: "Ordered",
  planned: "Planned",
  received: "Received",
};

const LIST_PERMISSION_DEFINITIONS = [
  {
    id: LIST_PERMISSIONS.VIEW,
    label: "View Lists",
    description: "View lists in authorized workspace, client, or project scopes.",
    operation: "read",
  },
  {
    id: LIST_PERMISSIONS.VIEW_ALL,
    label: "View All Lists",
    description: "View all lists in an authorized workspace scope.",
    operation: "read",
  },
  {
    id: LIST_PERMISSIONS.CREATE,
    label: "Create Lists",
    description: "Create lists in authorized workspace, client, or project scopes.",
    operation: "create",
  },
  {
    id: LIST_PERMISSIONS.UPDATE,
    label: "Update Lists",
    description: "Update list title, description, type, context, and editable metadata.",
    operation: "update",
  },
  {
    id: LIST_PERMISSIONS.COMPLETE,
    label: "Complete Lists",
    description: "Complete and reopen lists.",
    operation: "complete",
  },
  {
    id: LIST_PERMISSIONS.FINALIZE,
    label: "Finalize Lists",
    description: "Finalize reproducible historical lists and bill-of-materials records.",
    operation: "finalize",
  },
  {
    id: LIST_PERMISSIONS.ARCHIVE,
    label: "Archive Lists",
    description: "Archive lists while preserving historical access.",
    operation: "archive",
  },
  {
    id: LIST_PERMISSIONS.RESTORE,
    label: "Restore Lists",
    description: "Restore archived or deleted lists where allowed.",
    operation: "restore",
  },
  {
    id: LIST_PERMISSIONS.DELETE,
    label: "Delete Lists",
    description: "Soft-delete lists where allowed.",
    operation: "delete",
  },
  {
    id: LIST_PERMISSIONS.DUPLICATE,
    label: "Duplicate Lists",
    description: "Duplicate accessible lists into independent active working lists.",
    operation: "duplicate",
  },
  {
    id: LIST_PERMISSIONS.MANAGE_ITEMS,
    label: "Manage List Items",
    description: "Add, edit, reorder, check, uncheck, complete, and delete list items.",
    operation: "manage_items",
  },
  {
    id: LIST_PERMISSIONS.MANAGE_REUSABLE,
    label: "Manage Reusable Lists",
    description: "Mark and manage reusable lists used as reusable starting points.",
    operation: "manage_reusable",
  },
  {
    id: LIST_PERMISSIONS.MANAGE_CATALOG,
    label: "Manage List Catalog",
    description: "Manage reusable list item catalog entries when catalog workflows ship.",
    operation: "manage_catalog",
  },
  {
    id: LIST_PERMISSIONS.MANAGE_LINKS,
    label: "Manage List Links",
    description: "Link and unlink lists to authorized records when linked-record workflows ship.",
    operation: "manage_links",
  },
  {
    id: LIST_PERMISSIONS.MANAGE_SETTINGS,
    label: "Manage Lists Settings",
    description: "Manage workspace-level Lists settings.",
    operation: "manage",
  },
].map((permission) => ({
  ...permission,
  moduleId: LIST_MODULE_ID,
  resource: "lists",
}));

const ALL_LIST_PERMISSION_IDS = LIST_PERMISSION_DEFINITIONS.map((permission) => permission.id);
const INTERNAL_LIST_PERMISSION_IDS = [
  LIST_PERMISSIONS.VIEW,
  LIST_PERMISSIONS.CREATE,
  LIST_PERMISSIONS.UPDATE,
  LIST_PERMISSIONS.COMPLETE,
  LIST_PERMISSIONS.ARCHIVE,
  LIST_PERMISSIONS.RESTORE,
  LIST_PERMISSIONS.DELETE,
  LIST_PERMISSIONS.MANAGE_ITEMS,
];
const BASIC_LIST_PERMISSION_IDS = [
  LIST_PERMISSIONS.VIEW,
  LIST_PERMISSIONS.CREATE,
  LIST_PERMISSIONS.UPDATE,
  LIST_PERMISSIONS.COMPLETE,
  LIST_PERMISSIONS.MANAGE_ITEMS,
];

const listsModule = {
  id: LIST_MODULE_ID,
  name: "Lists",
  displayName: "Procurement Lists",
  description: "Operational shopping, procurement, packing, parts, bill of materials, and checklist-style lists.",
  terminology: {
    default: {
      label: "Lists",
      singular: "List",
      plural: "Lists",
      navigationLabel: "Lists",
      createButton: "Create List",
      emptyState: "No lists found.",
    },
    business: {
      label: "Procurement Lists",
      singular: "Procurement List",
      plural: "Procurement Lists",
      navigationLabel: "Procurement Lists",
      createButton: "Create Procurement List",
      emptyState: "No procurement lists found.",
    },
    personal: {
      label: "Shopping Lists",
      singular: "Shopping List",
      plural: "Shopping Lists",
      navigationLabel: "Shopping Lists",
      createButton: "Create Shopping List",
      emptyState: "No shopping lists found.",
    },
    family: {
      label: "Shopping Lists",
      singular: "Shopping List",
      plural: "Shopping Lists",
      navigationLabel: "Shopping Lists",
      createButton: "Create Shopping List",
      emptyState: "No shopping lists found.",
    },
  },
  category: "core-workflow",
  version: "0.33.5.21.0.6",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [listsRoutes],
  publicApiRoutes: [listsPublicApiRoutes],
  migrationsDir: null,
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    {
      id: "lists",
      label: "Lists",
      href: "lists.html",
      parent: "projects.html",
      requiredPermissions: [LIST_PERMISSIONS.VIEW],
      requiresEnabledModules: ["lists"],
      terminology: {
        business: { label: "Procurement Lists" },
        family: { label: "Shopping Lists" },
        personal: { label: "Shopping Lists" },
      },
    },
  ],
  protectedViews: [
    {
      id: "lists",
      path: "/lists.html",
      moduleId: LIST_MODULE_ID,
      file: "lists.html",
      requiredPermissions: [LIST_PERMISSIONS.VIEW],
      allowDisabledRead: true,
    },
  ],
  viewSurfaces: [
    {
      id: "lists.workspace",
      moduleId: LIST_MODULE_ID,
      viewId: "lists",
      layout: "stacked",
      pageHeader: {
        title: "Lists",
        titleKey: "label",
        primaryAction: {
          id: "create-list",
          label: "Create List",
          labelKey: "createButton",
          role: "primary",
          behavior: "lists.create",
          requiredPermissions: [LIST_PERMISSIONS.CREATE],
        },
      },
      filters: [
        {
          id: "status-filter",
          field: "status",
          type: "select",
          label: "Status",
          default: "active",
          options: [
            ["active", "Active", true],
            ["completed", "Completed"],
            ["finalized", "Finalized"],
            ["archived", "Archived"],
            ["deleted", "Deleted"],
            ["all", "All visible"],
          ],
        },
        {
          id: "type-filter",
          field: "listType",
          type: "select",
          label: "Type",
          default: "all",
          options: [
            ["all", "All types", true],
            ["bill_of_materials", "Bill of Materials"],
            ["checklist", "Checklist"],
            ["packing", "Packing"],
            ["parts", "Parts"],
            ["procurement", "Procurement"],
            ["shopping", "Shopping"],
            ["supplies", "Supplies"],
          ],
        },
        {
          id: "reusable-filter",
          field: "reusable",
          type: "select",
          label: "Reusable",
          default: "no",
          options: [
            ["no", "Normal lists", true],
            ["yes", "Reusable only"],
            ["all", "All"],
          ],
        },
        {
          id: "client-filter",
          field: "clientId",
          type: "select",
          label: "Client",
          default: "all",
          options: [["all", "All clients", true]],
        },
        {
          id: "project-filter",
          field: "projectId",
          type: "select",
          label: "Project",
          default: "all",
          options: [["all", "All projects", true]],
        },
        {
          id: "assignee-filter",
          field: "assigneeId",
          type: "select",
          label: "Assigned",
          default: "all",
          options: [["all", "All assignees", true]],
        },
        {
          id: "needed-filter",
          field: "neededByDate",
          type: "date",
          label: "Needed By",
        },
        {
          id: "archive-filter",
          field: "archiveState",
          type: "select",
          label: "Archived State",
          default: "current",
          options: [
            ["current", "Current", true],
            ["archived", "Archived"],
            ["deleted", "Deleted"],
            ["all", "All states"],
          ],
        },
        {
          id: "sort-filter",
          field: "sort",
          type: "select",
          label: "Sort",
          default: "updated_desc",
          options: [
            ["updated_desc", "Updated", true],
            ["title_asc", "Title"],
            ["type_asc", "Type"],
            ["status_asc", "Status"],
            ["needed_asc", "Needed Date"],
            ["finalized_desc", "Finalized Date"],
          ],
        },
      ],
      indexPanel: {
        title: "List Selector",
        itemTitleField: "title",
        itemSubtitleField: "description",
        initialSelection: "none",
        collapseOnSelect: true,
        emptyState: {
          title: "No lists",
          message: "No lists match the current filters.",
        },
      },
      detail: {
        header: {
          title: "Selected list",
          description: "Choose a list to inspect.",
        },
        actionStrip: {
          label: "List actions",
          actions: [
            { id: "duplicate-list", label: "Duplicate", role: "secondary", behavior: "lists.workflow.duplicate", requiredPermissions: [LIST_PERMISSIONS.DUPLICATE] },
            { id: "edit-list", label: "Edit", role: "secondary", behavior: "lists.workflow.edit", requiredPermissions: [LIST_PERMISSIONS.UPDATE] },
            { id: "complete-list", label: "Complete", role: "secondary", behavior: "lists.workflow.complete", requiredPermissions: [LIST_PERMISSIONS.COMPLETE] },
            { id: "finalize-list", label: "Finalize", role: "secondary", behavior: "lists.workflow.finalize", requiredPermissions: [LIST_PERMISSIONS.FINALIZE] },
            { id: "reopen-list", label: "Reopen", role: "secondary", behavior: "lists.workflow.reopen", requiredPermissions: [LIST_PERMISSIONS.UPDATE] },
            { id: "mark-reusable-list", label: "Mark Reusable", role: "secondary", behavior: "lists.workflow.mark-reusable", requiredPermissions: [LIST_PERMISSIONS.MANAGE_REUSABLE] },
            { id: "unmark-reusable-list", label: "Unmark Reusable", role: "secondary", behavior: "lists.workflow.unmark-reusable", requiredPermissions: [LIST_PERMISSIONS.MANAGE_REUSABLE] },
            { id: "archive-list", label: "Archive", role: "secondary", behavior: "lists.workflow.archive", requiredPermissions: [LIST_PERMISSIONS.ARCHIVE] },
            { id: "delete-list", label: "Delete", role: "destructive", behavior: "lists.workflow.delete", requiredPermissions: [LIST_PERMISSIONS.DELETE] },
            { id: "restore-list", label: "Restore", role: "secondary", behavior: "lists.workflow.restore", requiredPermissions: [LIST_PERMISSIONS.RESTORE] },
          ],
        },
        summaryPanels: [
          {
            title: "Next",
            description: "List progress and next action context.",
          },
          {
            title: "Source",
            description: "Template and working-copy context.",
          },
          {
            title: "Costs",
            description: "Estimated and actual item costs.",
          },
          {
            title: "Linked Records",
            description: "Task, note, project, and client links.",
          },
        ],
        linkedRecords: {
          title: "Linked Records",
          recordsField: "links",
          targetTypeField: "target_type",
          targetLabelField: "target.label",
          targetUrlField: "target.url",
          targetIdField: "list_link_id",
          emptyState: {
            message: "No linked records yet.",
          },
          fields: [
            { field: "target_type", type: "select", label: "Type", default: "task", options: [["task", "Task"], ["note", "Note"], ["project", "Project"], ["client", "Client"]] },
            { field: "task_search", type: "search", label: "Search tasks", placeholder: "Search tasks", autocomplete: "off", behavior: "lists.link.task-search" },
            { field: "task_picker", type: "select", label: "Task", optionsSource: "taskLinkTargets", behavior: "lists.link.task-picker" },
            { field: "target_id", type: "text", label: "Record ID", required: true, placeholder: "Paste record ID", behavior: "lists.link.raw-record-id" },
          ],
          actions: [
            { id: "add-link", label: "Add Link", role: "primary", behavior: "lists.link.add", requiredPermissions: [LIST_PERMISSIONS.MANAGE_LINKS] },
            { id: "remove-link", label: "Remove", role: "destructive", behavior: "lists.link.remove", requiredPermissions: [LIST_PERMISSIONS.MANAGE_LINKS] },
          ],
        },
        emptyState: {
          title: "Select a list",
          message: "Select a list to review its context.",
        },
        itemForm: {
          title: "Items",
          fields: [
            { field: "item_name", type: "text", label: "Item", required: true, autocomplete: "off", behavior: "lists.catalog-suggestions", width: "full" },
            { field: "catalog_item_id", type: "hidden", label: "Catalog Item" },
            { field: "quantity", type: "number", label: "Qty", default: "1", min: "0", step: "0.01", width: "narrow" },
            { field: "unit", type: "text", label: "Unit", width: "narrow" },
            { field: "needed_by_date", type: "date", label: "Needed by", width: "compact" },
            { field: "assigned_user_id", type: "select", label: "Assigned", optionsSource: "users", width: "compact" },
            { field: "purchase_status", type: "select", label: "Status", default: "needed", options: Object.entries(PURCHASE_STATUS_LABELS).map(([value, label]) => [value, label]), width: "compact" },
            { field: "vendor_name", type: "text", label: "Vendor or Store", placement: "advanced" },
            { field: "url", type: "url", label: "URL", placement: "advanced" },
            { field: "estimated_cost", type: "number", label: "Estimated Cost", min: "0", step: "0.01", placement: "advanced" },
            { field: "actual_cost", type: "number", label: "Actual Cost", min: "0", step: "0.01", placement: "advanced" },
            { field: "tracking_id", type: "text", label: "Tracking ID", placement: "advanced" },
            { field: "notes", type: "textarea", label: "Notes", rows: "2", width: "full" },
            { field: "save_to_catalog", type: "checkbox", label: "Save as reusable item", default: "true" },
          ],
          actions: [
            { id: "save-item", label: "Add Item", role: "primary", behavior: "lists.item.save", requiredPermissions: [LIST_PERMISSIONS.MANAGE_ITEMS] },
          ],
        },
        itemRows: {
          itemsField: "items",
          columns: [
            { id: "done", label: "Done", type: "checkbox" },
            { id: "item", field: "item_name", label: "Item" },
            { id: "quantity", field: "quantity", label: "Qty" },
            { id: "cost", field: "estimated_cost", label: "Cost" },
            { id: "needed", field: "needed_by_date", label: "Needed By" },
            { id: "status", field: "purchase_status", label: "Status" },
            { id: "actions", label: "Actions", type: "actions" },
          ],
          actions: [
            { id: "edit-item", label: "Edit", role: "secondary", behavior: "lists.item.edit", requiredPermissions: [LIST_PERMISSIONS.MANAGE_ITEMS] },
            { id: "move-item-up", label: "Up", role: "utility", behavior: "lists.item.move-up", requiredPermissions: [LIST_PERMISSIONS.MANAGE_ITEMS] },
            { id: "move-item-down", label: "Down", role: "utility", behavior: "lists.item.move-down", requiredPermissions: [LIST_PERMISSIONS.MANAGE_ITEMS] },
            { id: "delete-item", label: "Delete", role: "destructive", behavior: "lists.item.delete", requiredPermissions: [LIST_PERMISSIONS.MANAGE_ITEMS] },
          ],
          emptyState: {
            message: "No items yet.",
          },
        },
      },
      modals: [
        {
          id: "list-editor",
          title: "List",
          fields: [
            { field: "title", type: "text", label: "Title", required: true },
            { field: "list_type", type: "select", label: "Type", options: Object.entries(LIST_TYPE_LABELS).map(([value, label]) => [value, label]) },
            { field: "client_id", type: "select", label: "Client", optionsSource: "clients" },
            { field: "project_id", type: "select", label: "Project", optionsSource: "projects" },
            { field: "description", type: "textarea", label: "Description", rows: "4" },
          ],
          footerActions: [
            { id: "cancel-list", label: "Cancel", role: "secondary", behavior: "lists.modal.cancel" },
            { id: "save-list", label: "Save List", role: "primary", behavior: "lists.modal.save", requiredPermissions: [LIST_PERMISSIONS.CREATE, LIST_PERMISSIONS.UPDATE] },
          ],
        },
      ],
      dataSource: {
        route: "/api/lists",
        method: "GET",
        fieldBindings: {
          id: "list_id",
          title: "title",
          description: "description",
          status: "status",
          listType: "list_type",
          updatedAt: "updated_at",
        },
      },
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "lists-script",
      moduleId: LIST_MODULE_ID,
      path: "/js/lists.js",
      type: "script",
      views: ["lists"],
      requiredPermissions: [LIST_PERMISSIONS.VIEW],
    },
  ],
  dashboard: [],
  workbench: [],
  reporting: [],
  settings: [
    {
      id: "listsEnabled",
      label: "Lists",
      type: "boolean",
      moduleStatus: true,
      terminology: {
        business: {
          label: "Procurement Lists",
        },
        personal: {
          label: "Shopping Lists",
        },
        family: {
          label: "Shopping Lists",
        },
      },
    },
  ],
  requiredPermissions: ALL_LIST_PERMISSION_IDS,
  permissions: LIST_PERMISSION_DEFINITIONS,
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ALL_LIST_PERMISSION_IDS },
    { roleId: "workspace_admin", permissions: ALL_LIST_PERMISSION_IDS },
    { roleId: "client_admin", permissions: INTERNAL_LIST_PERMISSION_IDS },
    { roleId: "project_admin", permissions: INTERNAL_LIST_PERMISSION_IDS },
    { roleId: "client_user", permissions: BASIC_LIST_PERMISSION_IDS },
    { roleId: "project_user", permissions: BASIC_LIST_PERMISSION_IDS },
    { roleId: "client_external_user", permissions: [] },
  ],
  resourceDefinitions: [LIST_RESOURCE_DEFINITION],
  auditRecordTypes: LIST_AUDIT_RECORD_TYPES,
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/lists", scope: "lists:read" },
    { method: "GET", path: "/api/v1/lists/:listId", scope: "lists:read" },
  ],
  apiScopes: [
    {
      id: "lists:read",
      moduleId: LIST_MODULE_ID,
      label: "Read Lists",
      description: "Read lists through the public API.",
      access: "read",
    },
  ],
  eventTypes: LIST_EVENT_TYPES,
  eventSummaries: [],
  hooks: { events: [] },
  timerSources: [],
  workItemSources: [],
  taggableTypes: [
    {
      targetType: "list",
      moduleId: LIST_MODULE_ID,
      label: "List",
      description: "List records that can receive workspace tags.",
      tableName: "lists",
      idField: "list_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: LIST_PERMISSIONS.VIEW,
      requiredTagPermission: "tags.assign",
      requiredModules: ["lists"],
    },
  ],
  tagPropagation: [],
  searchableTypes: [
    {
      recordType: "list",
      moduleId: LIST_MODULE_ID,
      label: "List",
      description: "Lists searchable by title, description, list type, item names, linked context, and tags.",
      idField: "list_id",
      titleField: "title",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: LIST_PERMISSIONS.VIEW,
      indexer: "lists.records",
      requiredModules: ["lists"],
      tagsTextField: "tags_text",
      recordStatusField: "search_status",
      sourceLabel: "Lists",
    },
  ],
  attachableTypes: [
    {
      targetType: "list",
      moduleId: LIST_MODULE_ID,
      label: "List",
      description: "List records that can receive framework-managed file attachments.",
      tableName: "lists",
      idField: "list_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: LIST_PERMISSIONS.VIEW,
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "presentation", "text", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.context_updated", "file.attachment.removed"],
      requiredModules: ["lists"],
    },
  ],
  linkedContextProviders: [
    {
      id: "lists.list",
      moduleId: LIST_MODULE_ID,
      targetType: "list",
      label: "List",
      description: "Permission-safe list targets for shared Linked Context pickers.",
      provider: "lists.linked-context.lists",
      responseContract: LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT,
      requiredReadPermission: LIST_PERMISSIONS.VIEW,
      requiredPermissions: [LIST_PERMISSIONS.VIEW],
      requiredModules: [LIST_MODULE_ID],
    },
  ],
  notificationEvents: [],
  notificationFollowTargets: [],
  help: {
    sections: [
      {
        id: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Lists",
        description: "Current Lists behavior for shopping, procurement, packing, supplies, parts, reusable workflows, links, files, search, and recovery context.",
        sortOrder: 130,
        audience: "user",
        tags: ["lists", "shopping", "procurement"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
    ],
    articles: [
      {
        id: "lists.basics",
        slug: "lists-basics",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Using Lists",
        summary: "Create operational lists for shopping, procurement, packing, supplies, parts, and checklist-style work.",
        contentPath: "modules/lists/using-lists.md",
        sortOrder: 10,
        audience: "user",
        tags: ["lists", "basics"],
        relatedArticleIds: ["lists.items", "lists.reusable", "lists.links"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.items",
        slug: "lists-items",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "List Items and Progress",
        summary: "Track concrete items, needed dates, purchase status, checking, and completion separately.",
        contentPath: "modules/lists/list-items-and-progress.md",
        sortOrder: 20,
        audience: "user",
        tags: ["lists", "items", "progress"],
        relatedArticleIds: ["lists.statuses", "lists.resume-context"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.statuses",
        slug: "lists-statuses",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "List Statuses",
        summary: "Use active, completed, finalized, archived, and deleted states to preserve useful history.",
        contentPath: "modules/lists/list-statuses.md",
        sortOrder: 30,
        audience: "user",
        tags: ["lists", "status", "archive"],
        relatedArticleIds: ["lists.reusable", "lists.resume-context"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.reusable",
        slug: "lists-reusable",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Reusable Lists and Suggestions",
        summary: "Use reusable lists and catalog-backed suggestions to avoid rebuilding repeatable workflows.",
        contentPath: "modules/lists/reusable-lists-and-suggestions.md",
        sortOrder: 40,
        audience: "user",
        tags: ["lists", "reusable", "suggestions"],
        relatedArticleIds: ["lists.items", "lists.statuses"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.business-context",
        slug: "lists-business-context",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Business, Project, and Client Context",
        summary: "Use business context for procurement and project supply work without changing module boundaries.",
        contentPath: "modules/lists/business-project-and-client-context.md",
        sortOrder: 50,
        audience: "user",
        tags: ["lists", "clients", "projects"],
        relatedArticleIds: ["lists.links", "lists.search-tags-files"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.links",
        slug: "lists-linked-records",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Linked Records",
        summary: "Connect lists to tasks, notes, projects, and business clients without granting extra access.",
        contentPath: "modules/lists/linked-records.md",
        sortOrder: 60,
        audience: "user",
        tags: ["lists", "links", "context"],
        relatedArticleIds: ["lists.resume-context", "lists.search-tags-files"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.search-tags-files",
        slug: "lists-search-tags-files",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Search, Tags, and Files",
        summary: "Recover list work through framework search, tags, and file attachments without bypassing permissions.",
        contentPath: "modules/lists/search-tags-and-files.md",
        sortOrder: 70,
        audience: "user",
        tags: ["lists", "search", "tags", "files"],
        relatedArticleIds: ["lists.basics", "lists.links"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
      {
        id: "lists.resume-context",
        slug: "lists-resume-context",
        sectionId: "lists.overview",
        moduleId: LIST_MODULE_ID,
        title: "Resuming List Work",
        summary: "Use list progress, source context, and linked context to pick work back up safely.",
        contentPath: "modules/lists/resuming-list-work.md",
        sortOrder: 80,
        audience: "user",
        tags: ["lists", "resume work", "context"],
        relatedArticleIds: ["lists.items", "lists.links", "lists.statuses"],
        requiredModules: [LIST_MODULE_ID],
        requiredPermissions: [LIST_PERMISSIONS.VIEW],
      },
    ],
  },
  frameworkDependencies: [
    "module-access",
    "workspace-settings",
  ],
  moduleDependencies: [],
  workspaceCapabilityRequirements: [],
};

export { listsModule };
