import { LIST_MODULE_ID } from "./storage-contract.js";

const listsModule = {
  id: LIST_MODULE_ID,
  name: "Lists",
  displayName: "Procurement Lists",
  description: "Operational shopping, procurement, packing, parts, bill of materials, and checklist-style lists.",
  terminology: {
    default: {
      label: "Lists",
      singular: "List",
      plural: "Lists",
      navigationLabel: "Lists",
      createButton: "Create List",
      emptyState: "No lists found.",
    },
    business: {
      label: "Procurement Lists",
      singular: "Procurement List",
      plural: "Procurement Lists",
      navigationLabel: "Procurement Lists",
      createButton: "Create Procurement List",
      emptyState: "No procurement lists found.",
    },
    personal: {
      label: "Shopping Lists",
      singular: "Shopping List",
      plural: "Shopping Lists",
      navigationLabel: "Shopping Lists",
      createButton: "Create Shopping List",
      emptyState: "No shopping lists found.",
    },
    family: {
      label: "Shopping Lists",
      singular: "Shopping List",
      plural: "Shopping Lists",
      navigationLabel: "Shopping Lists",
      createButton: "Create Shopping List",
      emptyState: "No shopping lists found.",
    },
  },
  category: "core-workflow",
  version: "0.33.4.1",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [],
  publicApiRoutes: [],
  migrationsDir: new URL("./migrations/", import.meta.url),
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [],
  protectedViews: [],
  publicViews: [],
  browserAssets: [],
  dashboard: [],
  workbench: [],
  reporting: [],
  settings: [
    {
      id: "listsEnabled",
      label: "Lists",
      type: "boolean",
      moduleStatus: true,
      terminology: {
        business: {
          label: "Procurement Lists",
        },
        personal: {
          label: "Shopping Lists",
        },
        family: {
          label: "Shopping Lists",
        },
      },
    },
  ],
  requiredPermissions: [],
  permissions: [],
  defaultRolePermissions: [],
  resourceDefinitions: [],
  auditRecordTypes: [],
  publicApiEndpoints: [],
  apiScopes: [],
  eventTypes: [],
  eventSummaries: [],
  hooks: { events: [] },
  timerSources: [],
  workItemSources: [],
  taggableTypes: [],
  tagPropagation: [],
  searchableTypes: [],
  attachableTypes: [],
  notificationEvents: [],
  notificationFollowTargets: [],
  help: { sections: [], articles: [] },
  frameworkDependencies: [
    "module-access",
    "workspace-settings",
  ],
  moduleDependencies: [],
  workspaceCapabilityRequirements: [],
};

export { listsModule };
