-- Migration 070: generic_workspace_module_settings
-- Forward-only: do not edit this file after it has been applied.
-- Add the smallest schema or data change needed below; the migration runner owns the transaction.
CREATE TABLE workspace_module_settings (
  workspace_id TEXT NOT NULL,
  module_id TEXT NOT NULL,
  setting_id TEXT NOT NULL,
  setting_value_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (workspace_id, module_id, setting_id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id) ON DELETE CASCADE
);
