-- Migration 071: migrate_module_settings_ownership
-- Forward-only: do not edit this file after it has been applied.
INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'client-projects', 'defaultBillingRate', json_quote(COALESCE(default_billing_rate, '')), created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'client-projects', 'billingPeriodType', json_quote(billing_period_type), created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'client-projects', 'billingPeriodStartDay', CAST(billing_period_start_day AS TEXT), created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'time-tracking', 'fiscalYearStartMonth', CAST(fiscal_year_start_month AS TEXT), created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'time-tracking', 'fiscalYearStartDay', CAST(fiscal_year_start_day AS TEXT), created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'time-tracking', 'billingRoundingEnabled', CASE WHEN rounding_enabled = 1 THEN 'true' ELSE 'false' END, created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'time-tracking', 'billingRoundingIncrement', json_quote(rounding_increment), created_at, updated_at
FROM workspace_settings;

INSERT OR IGNORE INTO workspace_module_settings (
  workspace_id, module_id, setting_id, setting_value_json, created_at, updated_at
)
SELECT workspace_id, 'tasks', 'taskTimersEnabled', CASE WHEN task_timers_enabled = 1 THEN 'true' ELSE 'false' END, created_at, updated_at
FROM workspace_settings;

CREATE TABLE workspace_settings_next (
  workspace_id TEXT PRIMARY KEY,
  audit_logging_enabled INTEGER NOT NULL DEFAULT 1,
  audit_retention_days INTEGER NOT NULL DEFAULT 30,
  audit_settings_updated_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id)
);

INSERT INTO workspace_settings_next (
  workspace_id,
  audit_logging_enabled,
  audit_retention_days,
  audit_settings_updated_at,
  created_at,
  updated_at
)
SELECT
  workspace_id,
  audit_logging_enabled,
  audit_retention_days,
  audit_settings_updated_at,
  created_at,
  updated_at
FROM workspace_settings;

DROP TABLE workspace_settings;
ALTER TABLE workspace_settings_next RENAME TO workspace_settings;
