-- Migration 073: user_landing_preferences
-- Forward-only: do not edit this file after it has been applied.
-- Add the smallest schema or data change needed below; the migration runner owns the transaction.

ALTER TABLE users
ADD COLUMN preferred_login_landing TEXT NOT NULL DEFAULT 'dashboard'
CHECK (preferred_login_landing IN ('dashboard', 'workbench', 'tasks', 'notes', 'lists'));

ALTER TABLE users
ADD COLUMN preferred_workspace_switch_landing TEXT NOT NULL DEFAULT 'dashboard'
CHECK (preferred_workspace_switch_landing IN ('dashboard', 'workbench', 'tasks', 'notes', 'lists'));
