-- Migration 074: project_admin_project_scope
-- Forward-only: do not edit this file after it has been applied.

INSERT INTO user_role_assignments (
  assignment_id,
  workspace_id,
  user_id,
  role_id,
  scope_type,
  scope_id,
  client_id,
  project_id,
  permission_overrides_json,
  created_at,
  updated_at
)
SELECT
  legacy.assignment_id || ':project:' || projects.id,
  legacy.workspace_id,
  legacy.user_id,
  legacy.role_id,
  'project',
  projects.id,
  NULL,
  projects.id,
  legacy.permission_overrides_json,
  legacy.created_at,
  legacy.updated_at
FROM user_role_assignments AS legacy
INNER JOIN projects
  ON projects.workspace_id = legacy.workspace_id
  AND projects.client_id = legacy.scope_id
WHERE legacy.role_id = 'project_admin'
  AND legacy.scope_type = 'client';

DELETE FROM user_role_assignments
WHERE role_id = 'project_admin'
  AND scope_type = 'client';

UPDATE roles
SET description = 'Controls one project and its project assignments.',
    assignable_scope_type = 'project'
WHERE role_id = 'project_admin';
