-- Migration 075: workspace_backup_exports
-- Forward-only: do not edit this file after it has been applied.

CREATE TABLE workspace_backup_exports (
  backup_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  archive_filename TEXT NOT NULL,
  archive_sha256 TEXT NOT NULL,
  app_version TEXT NOT NULL,
  created_by_user_id TEXT,
  status TEXT NOT NULL DEFAULT 'created',
  secure_notes_recovery_required INTEGER NOT NULL DEFAULT 0,
  file_object_count INTEGER NOT NULL DEFAULT 0,
  file_object_bytes INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (created_by_user_id) REFERENCES users(user_id)
);

CREATE INDEX idx_workspace_backup_exports_workspace_created
  ON workspace_backup_exports(workspace_id, created_at DESC);
