-- Migration 076: workspace_deletion_lifecycle
-- Forward-only: do not edit this file after it has been applied.

CREATE TABLE workspace_deletion_lifecycle (
  workspace_id TEXT PRIMARY KEY,
  requested_by_user_id TEXT,
  requested_at TEXT NOT NULL,
  purge_after TEXT NOT NULL,
  backup_id TEXT,
  no_current_backup_acknowledged INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (requested_by_user_id) REFERENCES users(user_id),
  FOREIGN KEY (backup_id) REFERENCES workspace_backup_exports(backup_id),
  CHECK (purge_after > requested_at),
  CHECK (
    (backup_id IS NOT NULL AND no_current_backup_acknowledged = 0)
    OR (backup_id IS NULL AND no_current_backup_acknowledged = 1)
  )
);

CREATE INDEX idx_workspace_deletion_lifecycle_purge_after
  ON workspace_deletion_lifecycle(purge_after);
