-- Migration 077: workspace_purge_boundary
-- Forward-only: do not edit this file after it has been applied.
-- migration-foreign-keys: off

ALTER TABLE workspace_deletion_lifecycle
ADD COLUMN status TEXT NOT NULL DEFAULT 'pending_deletion'
CHECK (status IN ('pending_deletion', 'purging'));

ALTER TABLE workspace_deletion_lifecycle
ADD COLUMN purge_started_at TEXT;

ALTER TABLE workspace_deletion_lifecycle
ADD COLUMN purge_token TEXT;

CREATE TABLE workspace_purge_tombstones (
  purge_tombstone_id TEXT PRIMARY KEY,
  workspace_fingerprint TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL CHECK (status IN ('in_progress', 'complete')),
  requested_at TEXT NOT NULL,
  purge_started_at TEXT NOT NULL,
  purged_at TEXT,
  attempt_count INTEGER NOT NULL DEFAULT 1 CHECK (attempt_count > 0),
  file_object_count INTEGER NOT NULL DEFAULT 0,
  file_object_bytes INTEGER NOT NULL DEFAULT 0,
  database_row_count INTEGER NOT NULL DEFAULT 0,
  last_failure_class TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  CHECK (
    (status = 'in_progress' AND purged_at IS NULL)
    OR (status = 'complete' AND purged_at IS NOT NULL)
  )
);

CREATE INDEX idx_workspace_purge_tombstones_status_started
  ON workspace_purge_tombstones(status, purge_started_at);

-- Purging a user's only workspace must retain the install-level identity
-- without pointing it at an unrelated workspace. Authentication handles the
-- resulting zero-workspace identity explicitly; 0.33.17.7.15 will add its
-- restricted export-only recovery surface.
PRAGMA defer_foreign_keys = ON;
PRAGMA legacy_alter_table = OFF;

CREATE TABLE users_next (
  user_id TEXT PRIMARY KEY,
  home_workspace_id TEXT,
  username TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL DEFAULT '',
  alt_email TEXT,
  timezone TEXT NOT NULL DEFAULT 'America/New_York',
  password TEXT NOT NULL,
  theme_mode TEXT NOT NULL DEFAULT 'light',
  user_status TEXT NOT NULL DEFAULT 'active',
  protected_user TEXT NOT NULL DEFAULT 'no',
  active_workspace_id TEXT,
  open_external_links_new_tab INTEGER NOT NULL DEFAULT 0 CHECK (open_external_links_new_tab IN (0, 1)),
  theme_auto_source TEXT NOT NULL DEFAULT 'system' CHECK (theme_auto_source IN ('system')),
  password_change_required INTEGER NOT NULL DEFAULT 0,
  preferred_login_landing TEXT NOT NULL DEFAULT 'dashboard'
    CHECK (preferred_login_landing IN ('dashboard', 'workbench', 'tasks', 'notes', 'lists')),
  preferred_workspace_switch_landing TEXT NOT NULL DEFAULT 'dashboard'
    CHECK (preferred_workspace_switch_landing IN ('dashboard', 'workbench', 'tasks', 'notes', 'lists')),
  FOREIGN KEY (home_workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (active_workspace_id) REFERENCES workspaces(workspace_id)
);

INSERT INTO users_next (
  user_id,
  home_workspace_id,
  username,
  display_name,
  alt_email,
  timezone,
  password,
  theme_mode,
  user_status,
  protected_user,
  active_workspace_id,
  open_external_links_new_tab,
  theme_auto_source,
  password_change_required,
  preferred_login_landing,
  preferred_workspace_switch_landing
)
SELECT
  user_id,
  home_workspace_id,
  username,
  display_name,
  alt_email,
  timezone,
  password,
  theme_mode,
  user_status,
  protected_user,
  active_workspace_id,
  open_external_links_new_tab,
  theme_auto_source,
  password_change_required,
  preferred_login_landing,
  preferred_workspace_switch_landing
FROM users;

DROP TABLE users;
ALTER TABLE users_next RENAME TO users;

CREATE UNIQUE INDEX idx_users_unique_user_id
  ON users (user_id);
