-- Migration 078: account_export_recovery
-- Forward-only: do not edit this file after it has been applied.

CREATE TABLE account_export_recovery_qualifications (
  user_id TEXT PRIMARY KEY,
  qualification_basis TEXT NOT NULL CHECK (qualification_basis = 'former_workspace_administrator'),
  qualification_source TEXT NOT NULL CHECK (qualification_source IN ('membership_loss', 'membership_leave', 'workspace_purge')),
  qualified_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE sessions_next (
  session_id TEXT PRIMARY KEY,
  home_workspace_id TEXT,
  active_workspace_id TEXT,
  user_id TEXT NOT NULL,
  username TEXT NOT NULL,
  timezone TEXT NOT NULL DEFAULT 'America/New_York',
  ip_address TEXT,
  session_mode TEXT NOT NULL DEFAULT 'normal' CHECK (session_mode IN ('normal', 'account_export_recovery')),
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (home_workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (active_workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

INSERT INTO sessions_next (
  session_id,
  home_workspace_id,
  active_workspace_id,
  user_id,
  username,
  timezone,
  ip_address,
  session_mode,
  expires_at,
  created_at,
  updated_at
)
SELECT
  session_id,
  home_workspace_id,
  active_workspace_id,
  user_id,
  username,
  timezone,
  ip_address,
  'normal',
  expires_at,
  created_at,
  updated_at
FROM sessions;

DROP TABLE sessions;
ALTER TABLE sessions_next RENAME TO sessions;

CREATE INDEX idx_sessions_expires_at
ON sessions (expires_at);

CREATE INDEX idx_sessions_active_workspace
ON sessions (active_workspace_id);
