-- Migration 079: authentication_throttle_entries
-- Forward-only: do not edit this file after it has been applied.

CREATE TABLE authentication_throttle_entries (
  scope TEXT NOT NULL,
  dimension TEXT NOT NULL CHECK (dimension IN ('ip', 'account')),
  key_hash TEXT NOT NULL CHECK (length(key_hash) = 64),
  failure_count INTEGER NOT NULL CHECK (failure_count >= 0),
  window_expires_at INTEGER NOT NULL CHECK (window_expires_at >= 0),
  locked_until INTEGER NOT NULL DEFAULT 0 CHECK (locked_until >= 0),
  expires_at INTEGER NOT NULL CHECK (expires_at >= 0),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (scope, dimension, key_hash)
);

CREATE INDEX idx_authentication_throttle_expires_at
ON authentication_throttle_entries (expires_at);

CREATE INDEX idx_authentication_throttle_updated_at
ON authentication_throttle_entries (updated_at);
