-- Migration 080: startup_maintenance_runs
-- Forward-only: do not edit this file after it has been applied.
CREATE TABLE startup_maintenance_runs (
  maintenance_id TEXT PRIMARY KEY,
  lifecycle TEXT NOT NULL,
  completed_at TEXT NOT NULL,
  app_version TEXT NOT NULL,
  CHECK (lifecycle = 'one-time-migration-versioned-repair')
);
