-- Migration 081: task_estimate_minutes
-- Forward-only: do not edit this file after it has been applied.

ALTER TABLE tasks
ADD COLUMN estimate_minutes INTEGER
CHECK (
  estimate_minutes IS NULL
  OR (estimate_minutes >= 0 AND estimate_minutes % 15 = 0)
);

ALTER TABLE task_recurrence_templates
ADD COLUMN estimate_minutes INTEGER
CHECK (
  estimate_minutes IS NULL
  OR (estimate_minutes >= 0 AND estimate_minutes % 15 = 0)
);
