-- Migration 082: user_preferred_calendar_view
-- Forward-only: do not edit this file after it has been applied.

ALTER TABLE users
ADD COLUMN preferred_calendar_view TEXT
CHECK (preferred_calendar_view IS NULL OR preferred_calendar_view IN ('day', 'week', 'month'));
