-- Migration 083: task_recurrence_instance_uniqueness
-- Forward-only: do not edit this file after it has been applied.

CREATE UNIQUE INDEX IF NOT EXISTS idx_tasks_recurrence_instance_unique
ON tasks (workspace_id, recurrence_template_id, recurrence_instance_date);
