-- Migration 084: private_feed_tokens
-- Forward-only: do not edit this file after it has been applied.

CREATE TABLE private_feed_tokens (
  private_feed_token_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  provider_id TEXT NOT NULL,
  token_selector TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TEXT NOT NULL,
  rotated_at TEXT,
  disabled_at TEXT,
  updated_at TEXT NOT NULL,
  UNIQUE (workspace_id, user_id, provider_id),
  UNIQUE (provider_id, token_selector),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX idx_private_feed_tokens_authentication
ON private_feed_tokens (provider_id, token_selector, status);

CREATE INDEX idx_private_feed_tokens_user_workspace
ON private_feed_tokens (user_id, workspace_id, provider_id);
