-- Migration 085: named_calendar_subscriptions
-- Forward-only: do not edit this file after it has been applied.

PRAGMA foreign_keys = OFF;

CREATE TABLE private_feed_tokens_next (
  private_feed_token_id TEXT PRIMARY KEY,
  workspace_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  provider_id TEXT NOT NULL,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 120),
  scope_type TEXT NOT NULL DEFAULT 'workspace' CHECK (scope_type IN ('workspace', 'client', 'project')),
  scope_client_id TEXT,
  scope_project_id TEXT,
  token_selector TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  revocation_reason TEXT,
  created_at TEXT NOT NULL,
  rotated_at TEXT,
  revoked_at TEXT,
  updated_at TEXT NOT NULL,
  CHECK (
    (scope_type = 'workspace' AND scope_client_id IS NULL AND scope_project_id IS NULL)
    OR (scope_type = 'client' AND scope_client_id IS NOT NULL AND scope_project_id IS NULL)
    OR (scope_type = 'project' AND scope_project_id IS NOT NULL)
  ),
  UNIQUE (provider_id, token_selector),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id),
  FOREIGN KEY (workspace_id, scope_client_id) REFERENCES clients(workspace_id, id),
  FOREIGN KEY (workspace_id, scope_project_id) REFERENCES projects(workspace_id, id)
);

INSERT INTO private_feed_tokens_next (
  private_feed_token_id, workspace_id, user_id, provider_id, name, scope_type,
  scope_client_id, scope_project_id, token_selector, token_hash, status,
  revocation_reason, created_at, rotated_at, revoked_at, updated_at
)
SELECT
  legacy.private_feed_token_id, legacy.workspace_id, legacy.user_id, legacy.provider_id,
  'Calendar subscription', 'workspace', NULL, NULL, legacy.token_selector, legacy.token_hash,
  CASE
    WHEN legacy.status = 'active'
      AND users.user_status = 'active'
      AND memberships.status = 'active'
      AND lower(workspaces.status) = 'active'
      AND tasks_module.status = 'enabled'
      AND (
        users.protected_user = 'yes'
        OR EXISTS (
          SELECT 1
          FROM user_role_assignments
          INNER JOIN role_permissions ON role_permissions.role_id = user_role_assignments.role_id
          WHERE user_role_assignments.workspace_id = legacy.workspace_id
            AND user_role_assignments.user_id = legacy.user_id
            AND role_permissions.permission_id = 'tasks.view'
            AND user_role_assignments.scope_type IN ('all', 'workspace')
            AND COALESCE(json_extract(user_role_assignments.permission_overrides_json, '$.operationAccess.tasks.read'), 1) <> 0
        )
      )
    THEN 'active' ELSE 'revoked'
  END,
  CASE
    WHEN legacy.status <> 'active' THEN 'legacy_disabled'
    WHEN users.user_status = 'active'
      AND memberships.status = 'active'
      AND lower(workspaces.status) = 'active'
      AND tasks_module.status = 'enabled'
      AND (
        users.protected_user = 'yes'
        OR EXISTS (
          SELECT 1
          FROM user_role_assignments
          INNER JOIN role_permissions ON role_permissions.role_id = user_role_assignments.role_id
          WHERE user_role_assignments.workspace_id = legacy.workspace_id
            AND user_role_assignments.user_id = legacy.user_id
            AND role_permissions.permission_id = 'tasks.view'
            AND user_role_assignments.scope_type IN ('all', 'workspace')
            AND COALESCE(json_extract(user_role_assignments.permission_overrides_json, '$.operationAccess.tasks.read'), 1) <> 0
        )
      )
    THEN NULL
    WHEN users.user_id IS NULL OR users.user_status <> 'active' THEN 'owner_inactive'
    WHEN memberships.user_workspace_id IS NULL OR memberships.status <> 'active' THEN 'membership_inactive'
    WHEN workspaces.workspace_id IS NULL OR lower(workspaces.status) <> 'active' THEN 'workspace_inactive'
    WHEN tasks_module.workspace_id IS NULL OR tasks_module.status <> 'enabled' THEN 'tasks_module_disabled'
    ELSE 'tasks_permission_removed'
  END,
  legacy.created_at,
  legacy.rotated_at,
  CASE
    WHEN legacy.status = 'active'
      AND users.user_status = 'active'
      AND memberships.status = 'active'
      AND lower(workspaces.status) = 'active'
      AND tasks_module.status = 'enabled'
      AND (
        users.protected_user = 'yes'
        OR EXISTS (
          SELECT 1
          FROM user_role_assignments
          INNER JOIN role_permissions ON role_permissions.role_id = user_role_assignments.role_id
          WHERE user_role_assignments.workspace_id = legacy.workspace_id
            AND user_role_assignments.user_id = legacy.user_id
            AND role_permissions.permission_id = 'tasks.view'
            AND user_role_assignments.scope_type IN ('all', 'workspace')
            AND COALESCE(json_extract(user_role_assignments.permission_overrides_json, '$.operationAccess.tasks.read'), 1) <> 0
        )
      )
    THEN NULL ELSE COALESCE(legacy.disabled_at, legacy.updated_at)
  END,
  legacy.updated_at
FROM private_feed_tokens AS legacy
LEFT JOIN users ON users.user_id = legacy.user_id
LEFT JOIN user_workspaces AS memberships
  ON memberships.user_id = legacy.user_id AND memberships.workspace_id = legacy.workspace_id
LEFT JOIN workspaces ON workspaces.workspace_id = legacy.workspace_id
LEFT JOIN workspace_modules AS tasks_module
  ON tasks_module.workspace_id = legacy.workspace_id AND tasks_module.module_id = 'tasks';

DROP TABLE private_feed_tokens;
ALTER TABLE private_feed_tokens_next RENAME TO private_feed_tokens;

CREATE INDEX idx_private_feed_tokens_authentication
ON private_feed_tokens (provider_id, token_selector, status);
CREATE INDEX idx_private_feed_tokens_workspace
ON private_feed_tokens (workspace_id, provider_id, status, created_at);
CREATE INDEX idx_private_feed_tokens_owner
ON private_feed_tokens (user_id, workspace_id, provider_id, status);
CREATE INDEX idx_private_feed_tokens_scope
ON private_feed_tokens (workspace_id, provider_id, scope_type, scope_client_id, scope_project_id, status);

PRAGMA foreign_keys = ON;
