-- Migration 086: role_seed_scope_convergence
-- Forward-only: do not edit this file after it has been applied.

UPDATE roles
SET description = 'Controls one project and its project assignments.',
    assignable_scope_type = 'project'
WHERE role_id = 'project_admin'
  AND (
    description != 'Controls one project and its project assignments.'
    OR assignable_scope_type != 'project'
  );
