-- Migration 087: task_recurrence_recovery_checkpoint
-- Forward-only: do not edit this file after it has been applied.
ALTER TABLE task_recurrence_templates
ADD COLUMN recovery_checkpoint_date TEXT;
