-- Migration 088: secure_catalog_policy
-- Forward-only: do not edit this file after it has been applied.
ALTER TABLE note_library_collections
ADD COLUMN security_policy TEXT NOT NULL DEFAULT 'normal'
CHECK (security_policy IN ('normal', 'secure'));

ALTER TABLE note_library_collections
ADD COLUMN security_transition_state TEXT NOT NULL DEFAULT 'stable'
CHECK (security_transition_state IN ('stable', 'securing', 'failed'));

CREATE INDEX idx_note_library_collections_workspace_security
ON note_library_collections (workspace_id, security_policy, security_transition_state);
