-- Migration 089: secure_catalog_transitions
-- Forward-only: do not edit this file after it has been applied.

ALTER TABLE note_library_collections
  ADD COLUMN security_transition_action TEXT NOT NULL DEFAULT 'none'
    CHECK (security_transition_action IN ('none', 'enable', 'remove'));

ALTER TABLE note_library_collections
  ADD COLUMN security_transition_version INTEGER NOT NULL DEFAULT 0
    CHECK (security_transition_version >= 0);

ALTER TABLE note_library_collections
  ADD COLUMN security_transition_job_id TEXT;

ALTER TABLE note_library_collections
  ADD COLUMN security_transition_actor_user_id TEXT;

ALTER TABLE note_library_collections
  ADD COLUMN security_transition_started_at TEXT;

ALTER TABLE note_library_collections
  ADD COLUMN security_transition_error_code TEXT;
