-- Migration 091: support_view_action_events
-- Forward-only: do not edit this file after it has been applied.

ALTER TABLE support_view_events RENAME TO support_view_events_legacy;

CREATE TABLE support_view_events (
  event_id TEXT PRIMARY KEY,
  support_session_id TEXT NOT NULL,
  actor_user_id TEXT NOT NULL,
  effective_user_id TEXT NOT NULL,
  workspace_id TEXT NOT NULL,
  event_type TEXT NOT NULL
    CHECK (event_type IN ('entered', 'exited', 'expired', 'terminated', 'action_attempt')),
  outcome TEXT NOT NULL
    CHECK (outcome IN ('success', 'expired', 'revoked', 'disabled', 'allowed', 'denied')),
  request_id TEXT NOT NULL,
  route_id TEXT,
  action_id TEXT,
  reason_class TEXT,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  occurred_at TEXT NOT NULL,
  FOREIGN KEY (support_session_id) REFERENCES support_sessions(support_session_id),
  FOREIGN KEY (actor_user_id) REFERENCES users(user_id),
  FOREIGN KEY (effective_user_id) REFERENCES users(user_id),
  FOREIGN KEY (workspace_id) REFERENCES workspaces(workspace_id)
);

INSERT INTO support_view_events (
  event_id, support_session_id, actor_user_id, effective_user_id, workspace_id,
  event_type, outcome, request_id, metadata_json, occurred_at
)
SELECT
  event_id, support_session_id, actor_user_id, effective_user_id, workspace_id,
  event_type, outcome, request_id, metadata_json, occurred_at
FROM support_view_events_legacy;

DROP TABLE support_view_events_legacy;

CREATE INDEX support_view_events_session_time_idx
ON support_view_events (support_session_id, occurred_at, event_id);

CREATE INDEX support_view_events_workspace_time_idx
ON support_view_events (workspace_id, occurred_at, event_id);

CREATE INDEX support_view_events_action_time_idx
ON support_view_events (workspace_id, event_type, occurred_at, event_id);
-- Add the smallest schema or data change needed below; the migration runner owns the transaction.
