import { timeEntriesRoutes } from "./time-entries.routes.js";
import { timeTrackingPublicApiRoutes } from "./public-api.routes.js";

const timeTrackingModule = {
  id: "time-tracking",
  name: "Time Tracking",
  displayName: "Time Tracking",
  description: "Timers, manual entries, editable time entries, and billable time capture.",
  category: "core-workflow",
  version: "0.31.15",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [timeEntriesRoutes],
  publicApiRoutes: [timeTrackingPublicApiRoutes],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: new URL("./migrations/", import.meta.url),
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    { label: "Time Keeping", href: "time-tracker.html", parent: "projects.html" },
    { label: "Manual Entry", href: "manual-entry.html", parent: "time-tracker.html" },
    { label: "Edit Entries", href: "edit-entries.html", parent: "time-tracker.html" },
    { label: "Time Reports", href: "reporting.html", parent: "reporting.html" },
  ],
  protectedViews: [
    {
      id: "time-tracker",
      path: "/time-tracker.html",
      moduleId: "time-tracking",
      file: "time-tracker.html",
      requiredPermissions: ["time_entries.create"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
    },
    {
      id: "manual-entry",
      path: "/manual-entry.html",
      moduleId: "time-tracking",
      file: "manual-entry.html",
      requiredPermissions: ["time_entries.create"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
    },
    {
      id: "edit-entries",
      path: "/edit-entries.html",
      moduleId: "time-tracking",
      file: "edit-entries.html",
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      allowDisabledRead: true,
    },
    {
      id: "time-tracking-settings",
      path: "/time-tracking-settings.html",
      moduleId: "time-tracking",
      file: "time-tracking-settings.html",
      requiredPermissions: ["workspace_settings.manage"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "stop-watch-script",
      moduleId: "time-tracking",
      path: "/js/stop-watch.js",
      type: "script",
      views: ["time-tracker"],
      requiredPermissions: ["time_entries.create"],
    },
    {
      id: "manual-entry-script",
      moduleId: "time-tracking",
      path: "/js/manual-entry.js",
      type: "script",
      views: ["manual-entry"],
      requiredPermissions: ["time_entries.create"],
    },
    {
      id: "edit-entries-script",
      moduleId: "time-tracking",
      path: "/js/edit-entries.js",
      type: "script",
      views: ["edit-entries"],
    },
    {
      id: "time-tracking-module-settings-script",
      moduleId: "time-tracking",
      path: "/js/module-settings.js",
      type: "script",
      views: ["time-tracking-settings"],
      requiredPermissions: ["workspace_settings.manage"],
    },
  ],
  dashboard: [
    { id: "active-timers", label: "Active Timers" },
    { id: "recent-time", label: "Recent Time" },
    { id: "billing-summary", label: "Billing Summary" },
  ],
  workbench: [
    {
      id: "active-work-timers",
      label: "Active Timers",
      renderer: "active-work-timers",
      moduleId: "time-tracking",
      requiredPermissions: ["time_entries.create"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      requiresEnabledModules: ["time-tracking"],
      defaultCollapsed: false,
      sortOrder: 10,
    },
  ],
  reporting: [
    { id: "project-time-billing", label: "Project Time & Billing" },
  ],
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/time-entries", scope: "time_entries:read" },
    { method: "POST", path: "/api/v1/time-entries", scope: "time_entries:write" },
  ],
  requiredPermissions: [
    "time_entries.create",
    "time_entries.edit_own",
    "time_entries.edit_all",
    "reporting.view",
  ],
  workspaceCapabilityRequirements: ["time_tracking", "time_tracking_optional"],
  settings: [
    {
      id: "timeTrackingEnabled",
      label: "Time Tracking",
      type: "boolean",
      moduleStatus: true,
    },
  ],
  apiScopes: ["time_entries:read", "time_entries:write"],
  timerSources: [
    {
      sourceType: "manual",
      moduleId: "time-tracking",
      label: "Manual Timer",
      listRoute: "/api/active-timers",
      startRoute: "/api/active-timers/:timerSlot",
      pauseRoute: "/api/active-timers/:timerSlot",
      finalizeRoute: "/api/active-timers/:timerSlot/finalize",
      requiredPermissions: ["time_entries.create"],
      requiredModules: ["time-tracking"],
    },
  ],
  workItemSources: [],
  frameworkDependencies: [
    "api-key-auth",
    "audit-service",
    "billing-formatters",
    "client-projects",
    "module-access",
    "permissions-service",
    "timezone-normalization",
    "workspace-settings",
  ],
};

export { timeTrackingModule };
