import { timeEntriesRoutes } from "./time-entries.routes.js";
import { timeTrackingPublicApiRoutes } from "./public-api.routes.js";

const timeTrackingModule = {
  id: "time-tracking",
  name: "Time Tracking",
  displayName: "Time Tracking",
  description: "Timers, unified time entries, and billable time capture.",
  terminology: {
    default: {
      label: "Time Tracking",
      singular: "Time Entry",
      plural: "Time Entries",
      navigationLabel: "Time Tracking",
      createButton: "Create Time Entry",
      emptyState: "No time entries found.",
    },
  },
  category: "core-workflow",
  version: "0.32.5.4",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [timeEntriesRoutes],
  publicApiRoutes: [timeTrackingPublicApiRoutes],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: new URL("./migrations/", import.meta.url),
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    { label: "Time Keeping", href: "time-tracker.html", parent: "projects.html" },
    { label: "Time Entries", href: "time-entries.html", parent: "time-tracker.html" },
    { label: "Time Reports", href: "reporting.html", parent: "reporting.html" },
  ],
  protectedViews: [
    {
      id: "time-tracker",
      path: "/time-tracker.html",
      moduleId: "time-tracking",
      file: "time-tracker.html",
      requiredPermissions: ["time_entries.create"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
    },
    {
      id: "time-entries",
      path: "/time-entries.html",
      moduleId: "time-tracking",
      file: "time-entries.html",
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      allowDisabledRead: true,
    },
    {
      id: "time-tracking-settings",
      path: "/time-tracking-settings.html",
      moduleId: "time-tracking",
      file: "time-tracking-settings.html",
      requiredPermissions: ["workspace_settings.manage"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "stop-watch-script",
      moduleId: "time-tracking",
      path: "/js/stop-watch.js",
      type: "script",
      views: ["time-tracker"],
      requiredPermissions: ["time_entries.create"],
    },
    {
      id: "time-entry-dialog-script",
      moduleId: "time-tracking",
      path: "/js/time-entry-dialog.js",
      type: "script",
      views: ["time-entries", "workbench"],
    },
    {
      id: "time-entries-script",
      moduleId: "time-tracking",
      path: "/js/time-entries.js",
      type: "script",
      views: ["time-entries"],
    },
    {
      id: "time-tracking-module-settings-script",
      moduleId: "time-tracking",
      path: "/js/module-settings.js",
      type: "script",
      views: ["time-tracking-settings"],
      requiredPermissions: ["workspace_settings.manage"],
    },
  ],
  dashboard: [
    {
      id: "active-timers",
      label: "Active Timers",
      description: "Reserved active timer dashboard contribution.",
      renderer: "active-timers",
      moduleId: "time-tracking",
      requiredPermissions: ["time_entries.create"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      requiresEnabledModules: ["time-tracking"],
      sortOrder: 20,
    },
    {
      id: "recent-time",
      label: "Recent Time",
      description: "Reserved recent time dashboard contribution.",
      renderer: "recent-time",
      moduleId: "time-tracking",
      requiredPermissions: ["reporting.view"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      requiresEnabledModules: ["time-tracking"],
      sortOrder: 25,
    },
    {
      id: "billing-summary",
      label: "Billing Summary",
      description: "Current-month billables and trailing billables chart.",
      renderer: "billing-summary",
      moduleId: "time-tracking",
      requiredPermissions: ["reporting.view"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      requiresEnabledModules: ["time-tracking"],
      sortOrder: 40,
    },
  ],
  workbench: [
    {
      id: "active-work-timers",
      label: "Active Timers",
      description: "Active and paused timers with manual timer controls.",
      renderer: "active-work-timers",
      moduleId: "time-tracking",
      sourceType: "manual",
      listRoute: "/api/active-timers/all",
      requiredPermissions: ["time_entries.create"],
      requiredWorkspaceCapabilities: ["time_tracking", "time_tracking_optional"],
      requiresEnabledModules: ["time-tracking"],
      actions: [
        { id: "start", label: "Start", route: "/api/workbench/timers/:timerSlot/status" },
        { id: "pause", label: "Pause", route: "/api/workbench/timers/:timerSlot/status" },
        { id: "finalize", label: "Save & End", route: "/api/active-timers/:timerSlot/finalize" },
        { id: "discard", label: "Discard", route: "/api/active-timers/:timerSlot" },
      ],
      defaultCollapsed: false,
      sortOrder: 10,
    },
  ],
  reporting: [
    { id: "project-time-billing", label: "Project Time & Billing" },
  ],
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/time-entries", scope: "time_entries:read" },
    { method: "POST", path: "/api/v1/time-entries", scope: "time_entries:write" },
  ],
  requiredPermissions: [
    "time_entries.create",
    "time_entries.edit_own",
    "time_entries.edit_all",
    "reporting.view",
  ],
  permissions: [
    {
      id: "time_entries.create",
      moduleId: "time-tracking",
      label: "Create Time Entries",
      description: "Create stopwatch and manual time entries.",
      resource: "time_entries",
      operation: "create",
    },
    {
      id: "time_entries.edit_own",
      moduleId: "time-tracking",
      label: "Edit Own Time Entries",
      description: "Edit or delete only the actor's own time entries in scope.",
      resource: "time_entries",
      operation: "update",
    },
    {
      id: "time_entries.edit_all",
      moduleId: "time-tracking",
      label: "Edit All Time Entries",
      description: "Edit or delete time entries in scope.",
      resource: "time_entries",
      operation: "update",
    },
    {
      id: "reporting.view",
      moduleId: "time-tracking",
      label: "View Reporting",
      description: "View reports in scope.",
      resource: "reporting",
      operation: "read",
    },
  ],
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ["time_entries.create", "time_entries.edit_all", "reporting.view"] },
    { roleId: "workspace_admin", permissions: ["time_entries.create", "time_entries.edit_all", "reporting.view"] },
    { roleId: "client_admin", permissions: ["time_entries.create", "time_entries.edit_all", "reporting.view"] },
    { roleId: "project_admin", permissions: ["time_entries.create", "time_entries.edit_all", "reporting.view"] },
    { roleId: "client_user", permissions: ["time_entries.create", "time_entries.edit_own", "reporting.view"] },
    { roleId: "project_user", permissions: ["time_entries.create", "time_entries.edit_own", "reporting.view"] },
    { roleId: "client_external_user", permissions: ["time_entries.create", "time_entries.edit_own"] },
  ],
  resourceDefinitions: [
    {
      key: "time_entries",
      moduleId: "time-tracking",
      label: "Time Entries",
      operations: ["read", "create", "update", "delete", "manage"],
    },
    {
      key: "reporting",
      moduleId: "time-tracking",
      label: "Reporting",
      operations: ["read"],
    },
  ],
  auditRecordTypes: [
    {
      recordType: "time_entry",
      moduleId: "time-tracking",
      label: "Time Entry",
      description: "Tracked time records and time entry lifecycle audit history.",
    },
  ],
  taggableTypes: [
    {
      targetType: "time_entry",
      moduleId: "time-tracking",
      label: "Time Entry",
      description: "Tracked time records that can receive workspace tags.",
      tableName: "time_entries",
      idField: "entry_id",
      labelField: "description",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: "reporting.view",
      requiredTagPermission: "tags.assign",
      requiredModules: ["time-tracking"],
    },
  ],
  workspaceCapabilityRequirements: ["time_tracking", "time_tracking_optional"],
  settings: [
    {
      id: "timeTrackingEnabled",
      label: "Time Tracking",
      type: "boolean",
      moduleStatus: true,
    },
  ],
  apiScopes: [
    {
      id: "time_entries:read",
      moduleId: "time-tracking",
      label: "Read Time Entries",
      description: "Read time entries through the public API.",
      access: "read",
    },
    {
      id: "time_entries:write",
      moduleId: "time-tracking",
      label: "Write Time Entries",
      description: "Create time entries through the public API.",
      access: "write",
    },
  ],
  eventTypes: [
    {
      event: "timer.still_running",
      moduleId: "time-tracking",
      label: "Timer Still Running",
      description: "Reserved notification event for future long-running timer checks.",
      recordType: "active_work_timer",
    },
  ],
  eventSummaries: [
    {
      event: "timer.still_running",
      moduleId: "time-tracking",
      notification: {
        title: "Timer Still Running",
        body: "A timer is still running.",
        url: "workbench.html",
        recipientHints: ["actor"],
      },
    },
  ],
  notificationEvents: [
    {
      id: "timer.still_running",
      moduleId: "time-tracking",
      label: "Timer Still Running",
      description: "Notifies a user when a timer appears to still be running.",
      defaultEnabled: true,
      defaultPriority: "high",
      recipientMode: "actor",
    },
  ],
  timerSources: [
    {
      sourceType: "manual",
      moduleId: "time-tracking",
      label: "Manual Timer",
      listRoute: "/api/active-timers/all",
      startRoute: "/api/active-timers/:timerSlot",
      pauseRoute: "/api/active-timers/:timerSlot/pause",
      finalizeRoute: "/api/active-timers/:timerSlot/finalize",
      removeRoute: "/api/active-timers/:timerSlot",
      requiredPermissions: ["time_entries.create"],
      requiredModules: ["time-tracking"],
    },
  ],
  workItemSources: [],
  frameworkDependencies: [
    "api-key-auth",
    "audit-service",
    "billing-formatters",
    "client-projects",
    "module-access",
    "permissions-service",
    "timezone-normalization",
    "workspace-settings",
  ],
};

export { timeTrackingModule };
