import { tagsRoutes } from "../../routes/tags.routes.js";

const tagsModule = {
  id: "tags",
  name: "Tags",
  displayName: "Tags",
  description: "Workspace tag definitions, tag assignment APIs, and shared browser tagging controls.",
  terminology: {
    default: {
      label: "Tags",
      singular: "Tag",
      plural: "Tags",
      navigationLabel: "Tags",
      createButton: "Create Tag",
      emptyState: "No tags found.",
    },
  },
  category: "framework-service",
  version: "0.33.5.2.8",
  enabledByDefault: true,
  canDisable: false,
  historicalReadAccess: false,
  browserApiRoutes: [tagsRoutes],
  publicApiRoutes: [],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: null,
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    {
      label: "Tags",
      href: "tags.html",
      parent: "settings.html",
      requiredPermissions: ["tags.manage"],
    },
  ],
  protectedViews: [
    {
      id: "tags",
      path: "/tags.html",
      moduleId: "tags",
      file: "tags.html",
      requiredPermissions: ["tags.manage"],
      allowDisabledRead: false,
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "tags-management-script",
      moduleId: "tags",
      path: "/js/tags.js",
      type: "script",
      views: ["tags"],
      requiredPermissions: ["tags.manage"],
    },
    {
      id: "shared-tags-script",
      moduleId: "tags",
      path: "/js/shared/tags.js",
      type: "script",
      views: ["tasks", "time-tracker", "time-entries", "clients", "projects"],
      requiredPermissions: ["tags.view"],
    },
  ],
  dashboard: [],
  workbench: [],
  reporting: [],
  requiredPermissions: [
    "tags.manage",
    "tags.view",
    "tags.assign",
    "tags.remove",
  ],
  permissions: [
    {
      id: "tags.manage",
      moduleId: "tags",
      label: "Manage Tags",
      description: "Create, update, archive, disable, and restore workspace tag definitions.",
      resource: "tags",
      operation: "manage",
    },
    {
      id: "tags.view",
      moduleId: "tags",
      label: "View Tags",
      description: "View workspace tag definitions and assigned tags.",
      resource: "tags",
      operation: "read",
    },
    {
      id: "tags.assign",
      moduleId: "tags",
      label: "Assign Tags",
      description: "Assign workspace tags to taggable records.",
      resource: "tags",
      operation: "assign",
    },
    {
      id: "tags.remove",
      moduleId: "tags",
      label: "Remove Tags",
      description: "Remove tag assignments from taggable records.",
      resource: "tags",
      operation: "delete",
    },
  ],
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ["tags.manage", "tags.view", "tags.assign", "tags.remove"] },
    { roleId: "workspace_admin", permissions: ["tags.manage", "tags.view", "tags.assign", "tags.remove"] },
    { roleId: "client_admin", permissions: ["tags.view", "tags.assign", "tags.remove"] },
    { roleId: "project_admin", permissions: ["tags.view", "tags.assign", "tags.remove"] },
    { roleId: "client_user", permissions: ["tags.view", "tags.assign", "tags.remove"] },
    { roleId: "project_user", permissions: ["tags.view", "tags.assign", "tags.remove"] },
    { roleId: "client_external_user", permissions: ["tags.view"] },
  ],
  resourceDefinitions: [
    {
      key: "tags",
      moduleId: "tags",
      label: "Tags",
      operations: ["read", "create", "update", "delete", "archive", "restore", "assign", "manage"],
    },
  ],
  auditRecordTypes: [
    {
      recordType: "tag",
      moduleId: "tags",
      label: "Tag",
      description: "Workspace tag definition audit history.",
    },
    {
      recordType: "tag_assignment",
      moduleId: "tags",
      label: "Tag Assignment",
      description: "Workspace tag assignment audit history.",
    },
  ],
  publicApiEndpoints: [],
  apiScopes: [],
  eventTypes: [
    {
      event: "tag.assignment.manual_added",
      moduleId: "tags",
      label: "Manual Tag Assignment Added",
      description: "Emitted after a user directly assigns a tag to a record.",
      recordType: "tag_assignment",
    },
    {
      event: "tag.assignment.manual_removed",
      moduleId: "tags",
      label: "Manual Tag Assignment Removed",
      description: "Emitted after a user directly removes a tag assignment from a record.",
      recordType: "tag_assignment",
    },
    {
      event: "tag.assignment.propagated_added",
      moduleId: "tags",
      label: "Propagated Tag Assignment Added",
      description: "Emitted after the tag service materializes a propagated tag assignment.",
      recordType: "tag_assignment",
    },
    {
      event: "tag.assignment.propagated_removed",
      moduleId: "tags",
      label: "Propagated Tag Assignment Removed",
      description: "Emitted after the tag service removes a propagated tag assignment.",
      recordType: "tag_assignment",
    },
    {
      event: "tag.assignment.propagated_suppressed",
      moduleId: "tags",
      label: "Propagated Tag Assignment Suppressed",
      description: "Emitted after a propagated tag assignment is suppressed for a child record.",
      recordType: "tag_assignment",
    },
    {
      event: "tag.effective_tags.refreshed",
      moduleId: "tags",
      label: "Effective Tags Refreshed",
      description: "Emitted after effective tags are refreshed or a refresh request is safely skipped.",
      recordType: "tag_assignment",
    },
  ],
  eventSummaries: [],
  taggableTypes: [],
  tagPropagation: [],
  searchableTypes: [],
  notificationEvents: [],
  notificationTemplates: [],
  timerSources: [],
  workItemSources: [],
  frameworkDependencies: [
    "audit-service",
    "module-access",
    "permissions-service",
  ],
  moduleDependencies: [],
  workspaceCapabilityRequirements: [],
};

export { tagsModule };
