const STATIC_REGRESSIONS = Object.freeze([
  "scripts/check-js.mjs",
  "scripts/accessibility-regression.mjs",
  "scripts/event-bus-regression.mjs",
  "scripts/audit-extensibility-regression.mjs",
  "scripts/search-results-page-regression.mjs",
  "scripts/regression-runner-regression.mjs",
  "scripts/regression-clean-clone-contract.mjs",
  "scripts/tag-usability-ui-regression.mjs",
  "scripts/tag-inline-picker-regression.mjs",
  "scripts/tag-record-workflow-regression.mjs",
  "scripts/tag-management-page-regression.mjs",
  "scripts/file-ui-integration-regression.mjs",
  "scripts/module-file-closeout-regression.mjs",
  "scripts/notes-developer-docs-regression.mjs",
  "scripts/notes-context-terminology-regression.mjs",
  "scripts/linked-context-provider-contract-regression.mjs",
  "scripts/linked-context-picker-shell-regression.mjs",
  "scripts/notes-import-closeout-regression.mjs",
  "scripts/project-hierarchy-move-regression.mjs",
  "scripts/app-shell-navigation-regression.mjs",
  "scripts/module-sanity-check.mjs",
  "scripts/ui-contract-regression.mjs",
  "scripts/surface-token-contract-regression.mjs",
  "scripts/modal-section-contract-regression.mjs",
  "scripts/modal-footer-contract-regression.mjs",
  "scripts/overlay-host-contract-regression.mjs",
  "scripts/drawer-main-surface-contract-regression.mjs",
  "scripts/surface-adoption-pass-regression.mjs",
  "scripts/surface-standardization-closeout-regression.mjs",
  "scripts/view-builder-contract-regression.mjs",
  "scripts/view-builder-helper-regression.mjs",
  "scripts/lists-view-builder-pilot-regression.mjs",
  "scripts/view-builder-converted-surface-guardrails.mjs",
  "scripts/view-builder-closeout-regression.mjs",
  "scripts/view-descriptor-manifest-regression.mjs",
  "scripts/view-descriptor-reference-regression.mjs",
  "scripts/view-descriptor-terminology-regression.mjs",
  "scripts/view-descriptor-declarative-guardrails.mjs",
  "scripts/view-renderer-shell-regression.mjs",
  "scripts/view-descriptor-bootstrap-regression.mjs",
  "scripts/view-renderer-data-binding-regression.mjs",
  "scripts/view-index-primitive-regression.mjs",
  "scripts/view-shared-capabilities-regression.mjs",
  "scripts/view-renderer-actions-regression.mjs",
  "scripts/lists-declarative-readonly-surface-regression.mjs",
  "scripts/lists-items-modals-descriptor-regression.mjs",
  "scripts/lists-workflow-linked-layout-regression.mjs",
  "scripts/notes-declarative-readonly-surface-regression.mjs",
  "scripts/markdown-platform-contract-regression.mjs",
  "scripts/markdown-renderer-service-regression.mjs",
  "scripts/markdown-closeout-regression.mjs",
  "scripts/dashboard-workbench-regression.mjs",
  "scripts/task-list-density-regression.mjs",
  "scripts/task-list-canonical-ui-regression.mjs",
  "scripts/client-picker-hierarchy-regression.mjs",
  "scripts/client-modal-footer-actions-regression.mjs",
  "scripts/time-entries-screen-regression.mjs",
  "scripts/workbench-task-ordering-regression.mjs",
  "scripts/module-actions-regression.mjs",
  "scripts/shared-icons-regression.mjs",
  "scripts/icon-control-conversion-regression.mjs",
  "scripts/remaining-icon-actions-regression.mjs",
  "scripts/icon-accessibility-contract-regression.mjs",
]);

const DEFAULT_DATABASE_REGRESSIONS = Object.freeze([
  "scripts/search-contract-regression.mjs",
  "scripts/search-index-sync-regression.mjs",
  "scripts/search-rebuild-regression.mjs",
  "scripts/search-fts-repair-regression.mjs",
  "scripts/search-lifecycle-regression.mjs",
]);

const FILE_STORAGE_REGRESSIONS = Object.freeze([
  "scripts/file-framework-contract-regression.mjs",
  "scripts/file-api-lifecycle-regression.mjs",
  "scripts/file-storage-accounting-regression.mjs",
  "scripts/file-settings-regression.mjs",
  "scripts/files-attachment-readmodel-regression.mjs",
]);

const ISOLATED_DATABASE_REGRESSIONS = Object.freeze([
  "scripts/workspace-storage-regression.mjs",
  "scripts/legacy-cleanup-regression.mjs",
  "scripts/fresh-database-regression.mjs",
  "scripts/baseline-adoption-regression.mjs",
  "scripts/performance-regression.mjs",
  "scripts/notification-regression.mjs",
  "scripts/search-api-regression.mjs",
  "scripts/search-shell-regression.mjs",
  "scripts/search-workflow-regression.mjs",
  "scripts/help-contract-regression.mjs",
  "scripts/help-markdown-source-layout-regression.mjs",
  "scripts/help-center-surface-regression.mjs",
  "scripts/help-navigation-boundary-regression.mjs",
  "scripts/help-search-regression.mjs",
  "scripts/help-content-regression.mjs",
  "scripts/help-workflow-regression.mjs",
  "scripts/tag-service-regression.mjs",
  "scripts/tag-core-records-regression.mjs",
  "scripts/tag-propagation-foundation-regression.mjs",
  "scripts/tag-propagation-contract-regression.mjs",
  "scripts/tag-propagation-paths-regression.mjs",
  "scripts/tag-bulk-assignment-regression.mjs",
  "scripts/notes-foundation-regression.mjs",
  "scripts/notes-markdown-revision-regression.mjs",
  "scripts/notes-access-contract-regression.mjs",
  "scripts/notes-api-service-regression.mjs",
  "scripts/notes-search-help-regression.mjs",
  "scripts/notes-collections-regression.mjs",
  "scripts/notes-ui-workflow-regression.mjs",
  "scripts/notes-primary-context-regression.mjs",
  "scripts/linked-context-client-project-label-sort-regression.mjs",
  "scripts/linked-context-task-label-sort-regression.mjs",
  "scripts/linked-context-note-list-label-regression.mjs",
  "scripts/notes-task-context-regression.mjs",
  "scripts/notes-preview-editor-regression.mjs",
  "scripts/notes-secure-regression.mjs",
  "scripts/notes-integration-closeout-regression.mjs",
  "scripts/notes-linked-panel-regression.mjs",
  "scripts/notes-lists-tags-api-scope-regression.mjs",
  "scripts/lists-foundation-regression.mjs",
  "scripts/lists-service-regression.mjs",
  "scripts/lists-api-regression.mjs",
  "scripts/lists-ui-workflow-regression.mjs",
  "scripts/lists-closeout-regression.mjs",
  "scripts/lists-query-suggestions-regression.mjs",
  "scripts/personal-family-workspace-scope-regression.mjs",
  "scripts/client-projects-bugfix-regression.mjs",
  "scripts/client-projects-canonical-payload-regression.mjs",
  "scripts/api-key-scope-audit-regression.mjs",
  "scripts/public-api-client-project-write-regression.mjs",
  "scripts/task-resume-context-regression.mjs",
  "scripts/task-activity-metrics-regression.mjs",
  "scripts/task-recurrence-frequency-regression.mjs",
  "scripts/task-checklist-regression.mjs",
  "scripts/task-relationships-regression.mjs",
  "scripts/task-qol-closeout-regression.mjs",
  "scripts/task-bulk-due-tags-regression.mjs",
  "scripts/task-modal-compact-layout-regression.mjs",
  "scripts/task-modal-reflow-regression.mjs",
  "scripts/task-modal-followup-regression.mjs",
  "scripts/task-timer-status-regression.mjs",
  "scripts/timer-timestamp-integrity-regression.mjs",
  "scripts/timer-resume-metadata-regression.mjs",
  "scripts/work-resume-state-service-regression.mjs",
  "scripts/work-resume-state-producer-regression.mjs",
  "scripts/work-resume-state-initial-producers-regression.mjs",
  "scripts/work-resume-state-api-regression.mjs",
  "scripts/work-resume-state-closeout-regression.mjs",
  "scripts/files-time-tracking-qol-closeout-regression.mjs",
  "scripts/task-canonical-query-regression.mjs",
  "scripts/task-options-payload-regression.mjs",
  "scripts/project-default-assignee-regression.mjs",
]);

const REGRESSION_BUCKETS = Object.freeze([
  Object.freeze({
    concurrency: 6,
    mode: "parallel",
    name: "static/source regressions",
    scripts: STATIC_REGRESSIONS,
  }),
  Object.freeze({
    concurrency: 1,
    mode: "serial",
    name: "default database regressions",
    scripts: DEFAULT_DATABASE_REGRESSIONS,
  }),
  Object.freeze({
    concurrency: 1,
    mode: "serial",
    name: "file storage regressions",
    scripts: FILE_STORAGE_REGRESSIONS,
  }),
  Object.freeze({
    concurrency: 4,
    mode: "parallel",
    name: "isolated database regressions",
    scripts: ISOLATED_DATABASE_REGRESSIONS,
  }),
]);

const REGRESSION_SCRIPTS = Object.freeze(REGRESSION_BUCKETS.flatMap((bucket) => bucket.scripts));
const REGRESSION_COMMANDS = Object.freeze(REGRESSION_SCRIPTS.map((script) => `node ${script}`));

export {
  DEFAULT_DATABASE_REGRESSIONS,
  FILE_STORAGE_REGRESSIONS,
  ISOLATED_DATABASE_REGRESSIONS,
  REGRESSION_BUCKETS,
  REGRESSION_COMMANDS,
  REGRESSION_SCRIPTS,
  STATIC_REGRESSIONS,
};
