import { clientsRoutes } from "./clients.routes.js";
import { registerClientProjectsSearchIndexers } from "./search-indexers.js";
import { LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT } from "../../core/linked-context/provider-contract.js";

registerClientProjectsSearchIndexers();

const clientProjectsModule = {
  id: "client-projects",
  name: "Clients and Projects",
  displayName: "Clients and Projects",
  description: "Client and project records, billing defaults, and workspace-scoped project context.",
  terminology: {
    default: {
      label: "Clients and Projects",
      singular: "Project",
      plural: "Projects",
      navigationLabel: "Projects",
    },
    business: {
      label: "Clients & Projects",
      singular: "Client or Project",
      plural: "Clients & Projects",
      navigationLabel: "Clients & Projects",
    },
    personal: {
      label: "Projects",
      singular: "Project",
      plural: "Projects",
      navigationLabel: "Projects",
    },
  },
  category: "core-workflow",
  version: "0.33.5.21.7.7",
  enabledByDefault: true,
  canDisable: false,
  historicalReadAccess: true,
  browserApiRoutes: [clientsRoutes],
  publicApiRoutes: [],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: null,
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    { label: "Projects", href: "projects.html" },
    { label: "Clients", href: "clients.html", parent: "projects.html" },
  ],
  protectedViews: [
    {
      id: "clients",
      path: "/clients.html",
      moduleId: "client-projects",
      file: "clients.html",
      requiredWorkspaceCapabilities: ["clients_projects"],
    },
    {
      id: "projects",
      path: "/projects.html",
      moduleId: "client-projects",
      file: "projects.html",
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
    },
  ],
  viewSurfaces: [
    {
      id: "client-projects.clients",
      moduleId: "client-projects",
      viewId: "clients",
      layout: "table-page",
      filterPlacement: "slide-out-sidebar",
      sidebarLabel: "Filters",
      sidebarPanels: [
        {
          id: "client-projects-clients-filters",
          type: "filters",
          title: "Filters",
          open: true,
        },
      ],
      pageHeader: {
        title: "Clients",
        description: "Review client records, hierarchy, billing defaults, and tags.",
        primaryAction: {
          id: "add-client",
          label: "Add Client",
          role: "primary",
          behavior: "client-projects.clients.create",
          requiredPermissions: ["clients.manage"],
        },
      },
      filters: [
        {
          id: "client-status-filter",
          field: "status",
          type: "select",
          label: "Client Status",
          default: "Active",
          options: [
            ["Active", "Active", true],
            ["Inactive", "Inactive"],
            ["All", "All"],
          ],
        },
        {
          id: "client-tag-filter",
          field: "tagIds",
          queryKey: "tagIds",
          type: "search",
          label: "Tag",
          default: "",
          optionsSource: "client-projects.clients.tags",
        },
      ],
      indexPanel: {
        title: "Client hierarchy",
        itemTitleField: "displayLabel",
        itemSubtitleField: "status",
        itemMetaFields: ["billingDisplay", "tagSummary"],
        itemDepthField: "depth",
        itemParentField: "parentClientId",
        itemPathField: "displayPath",
        initialSelection: "none",
        emptyState: {
          title: "No clients",
        },
      },
      table: {
        hierarchy: {
          depthField: "depth",
          parentField: "parentClientId",
          pathField: "displayPath",
        },
        selection: {
          enabled: true,
          label: "Select Client",
          recordType: "client",
          labelField: "name",
        },
        columns: [
          {
            id: "client-name",
            field: "name",
            label: "Client",
            formatter: "hierarchy-label",
            depthField: "depth",
          },
          { id: "client-status", field: "status", label: "Status" },
          { id: "client-billable", field: "billingDisplay", label: "Billing" },
        ],
        secondaryRows: [
          {
            id: "client-tags",
            label: "Tags",
            field: "tags",
            formatter: "chip-list",
            chipsField: "tags",
            chipLabelField: "name",
            startColumn: "name",
            endBeforeColumn: "__view_row_actions",
            hideWhenEmpty: true,
          },
        ],
        rowActions: [
          {
            id: "edit-client",
            label: "Edit Client",
            role: "utility",
            icon: "edit",
            iconOnly: true,
            title: "Edit Client",
            behavior: "client-projects.clients.edit",
            requiredPermissions: ["clients.manage"],
          },
        ],
        emptyState: {
          title: "No clients",
        },
      },
      regions: [
        {
          id: "client-projects-clients-bulk",
          behavior: "client-projects.clients.bulk",
          placement: "before-table",
          className: "client-projects-bulk-region",
          ariaLabel: "Client bulk actions",
        },
      ],
      dataSource: {
        route: "/api/clients?include_depth=true",
        method: "GET",
        fieldBindings: {
          id: "id",
          name: "name",
          displayLabel: "display_label",
          status: "status",
          parentClientId: "parent_client_id",
          depth: "depth",
          displayPath: "display_path",
          billable: "billable",
          billingRate: "billing_rate",
          billingPeriod: "billing_period",
          billingRounding: "billing_rounding",
          tags: "tags",
          billingDisplay: "billing_display",
          tagSummary: "tag_summary",
        },
      },
    },
    {
      id: "client-projects.projects",
      moduleId: "client-projects",
      viewId: "projects",
      layout: "table-page",
      filterPlacement: "slide-out-sidebar",
      sidebarLabel: "Filters",
      sidebarPanels: [
        {
          id: "client-projects-projects-filters",
          type: "filters",
          title: "Filters",
          open: true,
        },
      ],
      pageHeader: {
        title: "Projects",
        description: "Review project records, hierarchy, client context, billing defaults, and tags.",
        primaryAction: {
          id: "add-project",
          label: "Add Project",
          role: "primary",
          behavior: "client-projects.projects.create",
          requiredPermissions: ["projects.manage"],
        },
      },
      filters: [
        {
          id: "project-client-filter",
          field: "clientId",
          queryKey: "clientId",
          type: "select",
          label: "Client",
          default: "All",
          optionsSource: "client-projects.projects.clients",
          options: [["All", "All clients", true]],
        },
        {
          id: "project-status-filter",
          field: "status",
          type: "select",
          label: "Status",
          default: "Active",
          options: [
            ["Active", "Active", true],
            ["Inactive", "Inactive"],
            ["Completed", "Completed"],
            ["All", "All"],
          ],
        },
        {
          id: "project-tag-filter",
          field: "tagIds",
          queryKey: "tagIds",
          type: "search",
          label: "Tag",
          default: "",
          optionsSource: "client-projects.projects.tags",
        },
      ],
      indexPanel: {
        title: "Project hierarchy",
        itemTitleField: "displayLabel",
        itemSubtitleField: "clientName",
        itemMetaFields: ["status", "billingDisplay", "tagSummary"],
        itemDepthField: "depth",
        itemParentField: "parentProjectId",
        itemPathField: "displayPath",
        initialSelection: "none",
        emptyState: {
          title: "No projects",
        },
      },
      table: {
        hierarchy: {
          depthField: "depth",
          parentField: "parentProjectId",
          pathField: "displayPath",
        },
        selection: {
          enabled: true,
          label: "Select Project",
          recordType: "project",
          labelField: "name",
        },
        columns: [
          {
            id: "project-name",
            field: "name",
            label: "Project",
            formatter: "hierarchy-label",
            depthField: "depth",
          },
          { id: "project-client", field: "clientName", label: "Client" },
          { id: "project-status", field: "status", label: "Status" },
          { id: "project-billable", field: "billingDisplay", label: "Billing" },
        ],
        secondaryRows: [
          {
            id: "project-tags",
            label: "Tags",
            field: "tags",
            formatter: "chip-list",
            chipsField: "tags",
            chipLabelField: "name",
            startColumn: "name",
            endBeforeColumn: "__view_row_actions",
            hideWhenEmpty: true,
          },
        ],
        rowActions: [
          {
            id: "edit-project",
            label: "Edit Project",
            role: "utility",
            icon: "edit",
            iconOnly: true,
            title: "Edit Project",
            behavior: "client-projects.projects.edit",
            requiredPermissions: ["projects.manage"],
          },
        ],
        emptyState: {
          title: "No projects",
        },
      },
      regions: [
        {
          id: "client-projects-projects-bulk",
          behavior: "client-projects.projects.bulk",
          placement: "before-table",
          className: "client-projects-bulk-region",
          ariaLabel: "Project bulk actions",
        },
      ],
      dataSource: {
        route: "/api/projects?include_depth=true",
        method: "GET",
        fieldBindings: {
          id: "id",
          name: "name",
          displayLabel: "display_label",
          status: "status",
          clientId: "client_id",
          clientName: "client_name",
          parentProjectId: "parent_project_id",
          parentProjectName: "parent_project_name",
          depth: "depth",
          displayPath: "display_path",
          billable: "billable",
          billingRate: "billing_rate",
          billingPeriod: "billing_period",
          billingRounding: "billing_rounding",
          taskDefaults: "taskDefaults",
          tags: "tags",
          billingDisplay: "billing_display",
          tagSummary: "tag_summary",
        },
      },
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "clients-projects-script",
      moduleId: "client-projects",
      path: "/js/clients-projects.js",
      type: "script",
      views: ["clients", "projects", "workbench"],
    },
  ],
  dashboard: [
    {
      id: "project-summary",
      label: "Project Summary",
      description: "Framework project/client hub data for dashboard reporting shortcuts.",
      renderer: "project-summary",
      moduleId: "client-projects",
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
      sortOrder: 10,
      terminology: {
        business: { label: "Client & Project Summary" },
        personal: { label: "Project Summary" },
      },
    },
  ],
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/clients", scope: "clients:read" },
    { method: "POST", path: "/api/v1/clients", scope: "clients:write" },
    { method: "GET", path: "/api/v1/clients/:clientId", scope: "clients:read" },
    { method: "PUT", path: "/api/v1/clients/:clientId", scope: "clients:write" },
    { method: "DELETE", path: "/api/v1/clients/:clientId", scope: "clients:write" },
    { method: "GET", path: "/api/v1/projects", scope: "projects:read" },
    { method: "POST", path: "/api/v1/projects", scope: "projects:write" },
    { method: "POST", path: "/api/v1/clients/:clientId/projects", scope: "projects:write" },
    { method: "GET", path: "/api/v1/projects/:projectId", scope: "projects:read" },
    { method: "PUT", path: "/api/v1/projects/:projectId", scope: "projects:write" },
    { method: "DELETE", path: "/api/v1/projects/:projectId", scope: "projects:write" },
  ],
  requiredPermissions: [
    "clients.manage",
    "projects.manage",
    "billing.manage",
  ],
  permissions: [
    {
      id: "clients.manage",
      moduleId: "client-projects",
      label: "Manage Clients",
      description: "Create, update, archive, and view clients.",
      resource: "clients",
      operation: "manage",
    },
    {
      id: "projects.manage",
      moduleId: "client-projects",
      label: "Manage Projects",
      description: "Create, update, archive, and view projects.",
      resource: "projects",
      operation: "manage",
    },
    {
      id: "billing.manage",
      moduleId: "client-projects",
      label: "Manage Billing Details",
      description: "Change billable status, rates, billing periods, and rounding.",
      resource: "billing",
      operation: "manage",
    },
  ],
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ["clients.manage", "projects.manage", "billing.manage"] },
    { roleId: "workspace_admin", permissions: ["clients.manage", "projects.manage", "billing.manage"] },
    { roleId: "client_admin", permissions: ["clients.manage", "projects.manage", "billing.manage"] },
    { roleId: "project_admin", permissions: ["projects.manage", "billing.manage"] },
  ],
  resourceDefinitions: [
    {
      key: "clients",
      moduleId: "client-projects",
      label: "Clients",
      operations: ["read", "create", "update", "archive", "restore", "manage"],
    },
    {
      key: "projects",
      moduleId: "client-projects",
      label: "Projects",
      operations: ["read", "create", "update", "archive", "restore", "manage"],
    },
    {
      key: "billing",
      moduleId: "client-projects",
      label: "Billing",
      operations: ["read", "update", "manage"],
    },
  ],
  auditRecordTypes: [
    {
      recordType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records and client lifecycle audit history.",
    },
    {
      recordType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records and project lifecycle audit history.",
    },
  ],
  taggableTypes: [
    {
      targetType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records that can receive workspace tags.",
      tableName: "clients",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      requiredReadPermission: "clients.manage",
      requiredTagPermission: "tags.assign",
      requiredModules: ["client-projects"],
    },
    {
      targetType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records that can receive workspace tags.",
      tableName: "projects",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      clientField: "client_id",
      requiredReadPermission: "projects.manage",
      requiredTagPermission: "tags.assign",
      requiredModules: ["client-projects"],
    },
  ],
  attachableTypes: [
    {
      targetType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records that can receive framework-managed file attachments.",
      tableName: "clients",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      requiredReadPermission: "clients.manage",
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.context_updated", "file.attachment.removed"],
      requiredModules: ["client-projects"],
      workspaceTypes: ["business"],
    },
    {
      targetType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records that can receive framework-managed file attachments.",
      tableName: "projects",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      clientField: "client_id",
      requiredReadPermission: "projects.manage",
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "presentation", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.context_updated", "file.attachment.removed"],
      requiredModules: ["client-projects"],
    },
  ],
  linkedContextProviders: [
    {
      id: "client-projects.client",
      moduleId: "client-projects",
      targetType: "client",
      label: "Client",
      description: "Permission-safe client targets for shared Linked Context pickers.",
      provider: "client-projects.linked-context.clients",
      responseContract: LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT,
      requiredReadPermission: "clients.manage",
      requiredPermissions: ["clients.manage"],
      requiredModules: ["client-projects"],
      requiredWorkspaceCapabilities: ["clients_projects"],
      workspaceTypes: ["business"],
    },
    {
      id: "client-projects.project",
      moduleId: "client-projects",
      targetType: "project",
      label: "Project",
      description: "Permission-safe project targets for shared Linked Context pickers.",
      provider: "client-projects.linked-context.projects",
      responseContract: LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT,
      requiredReadPermission: "projects.manage",
      requiredPermissions: ["projects.manage"],
      requiredModules: ["client-projects"],
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
    },
  ],
  tagPropagation: [
    {
      id: "client-projects.client-parent-to-child",
      sourceModuleId: "client-projects",
      sourceTargetType: "client",
      targetModuleId: "client-projects",
      targetType: "client",
      relationshipResolver: "client-projects.client-children",
      workspaceField: "workspace_id",
      sourceReadPermission: "clients.manage",
      targetReadPermission: "clients.manage",
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
    {
      id: "client-projects.client-to-project",
      sourceModuleId: "client-projects",
      sourceTargetType: "client",
      targetModuleId: "client-projects",
      targetType: "project",
      relationshipResolver: "client-projects.client-projects",
      workspaceField: "workspace_id",
      sourceReadPermission: "clients.manage",
      targetReadPermission: "projects.manage",
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
    {
      id: "client-projects.project-parent-to-child",
      sourceModuleId: "client-projects",
      sourceTargetType: "project",
      targetModuleId: "client-projects",
      targetType: "project",
      relationshipResolver: "client-projects.project-children",
      workspaceField: "workspace_id",
      sourceReadPermission: "projects.manage",
      targetReadPermission: "projects.manage",
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
  ],
  searchableTypes: [
    {
      recordType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records searchable by name, billing contact context, and tags.",
      idField: "id",
      titleField: "name",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      requiredReadPermission: "clients.manage",
      indexer: "client-projects.clients",
      requiredModules: ["client-projects"],
      tagsTextField: "tags_text",
      recordStatusField: "search_status",
      sourceLabel: "Client",
    },
    {
      recordType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records searchable by name, client/parent project context, defaults, and tags.",
      idField: "id",
      titleField: "name",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      clientField: "client_id",
      requiredReadPermission: "projects.manage",
      indexer: "client-projects.projects",
      requiredModules: ["client-projects"],
      tagsTextField: "tags_text",
      recordStatusField: "search_status",
      sourceLabel: "Project",
    },
  ],
  apiScopes: [
    {
      id: "clients:read",
      moduleId: "client-projects",
      label: "Read Clients",
      description: "Read client records through the public API.",
      access: "read",
      workspaceTypes: ["business"],
    },
    {
      id: "clients:write",
      moduleId: "client-projects",
      label: "Write Clients",
      description: "Create, update, and archive client records through the public API.",
      access: "write",
      workspaceTypes: ["business"],
    },
    {
      id: "projects:read",
      moduleId: "client-projects",
      label: "Read Projects",
      description: "Read project records through the public API.",
      access: "read",
    },
    {
      id: "projects:write",
      moduleId: "client-projects",
      label: "Write Projects",
      description: "Create, update, and archive project records through the public API.",
      access: "write",
    },
  ],
  settings: [
    {
      id: "clientProjectsEnabled",
      label: "Projects",
      type: "boolean",
      moduleStatus: true,
      description: "Required project and workspace context module.",
      terminology: {
        business: { label: "Clients & Projects" },
        personal: { label: "Projects" },
        family: { label: "Projects" },
      },
    },
  ],
  workbench: [],
  timerSources: [],
  workItemSources: [],
  workspaceCapabilityRequirements: ["clients_projects", "projects"],
};

export { clientProjectsModule };
