import { clientsRoutes } from "./clients.routes.js";
import { registerClientProjectsSearchIndexers } from "./search-indexers.js";

registerClientProjectsSearchIndexers();

const clientProjectsModule = {
  id: "client-projects",
  name: "Clients and Projects",
  displayName: "Clients and Projects",
  description: "Client and project records, billing defaults, and workspace-scoped project context.",
  terminology: {
    default: {
      label: "Clients and Projects",
      singular: "Project",
      plural: "Projects",
      navigationLabel: "Projects",
    },
    business: {
      label: "Clients & Projects",
      singular: "Client or Project",
      plural: "Clients & Projects",
      navigationLabel: "Clients & Projects",
    },
    personal: {
      label: "Projects",
      singular: "Project",
      plural: "Projects",
      navigationLabel: "Projects",
    },
  },
  category: "core-workflow",
  version: "0.33.5.15.4",
  enabledByDefault: true,
  canDisable: false,
  historicalReadAccess: true,
  browserApiRoutes: [clientsRoutes],
  publicApiRoutes: [],
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  migrationsDir: new URL("./migrations/", import.meta.url),
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    { label: "Projects", href: "projects.html" },
    { label: "Clients", href: "clients.html", parent: "projects.html" },
  ],
  protectedViews: [
    {
      id: "clients",
      path: "/clients.html",
      moduleId: "client-projects",
      file: "clients.html",
      requiredWorkspaceCapabilities: ["clients_projects"],
    },
    {
      id: "projects",
      path: "/projects.html",
      moduleId: "client-projects",
      file: "projects.html",
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "clients-projects-script",
      moduleId: "client-projects",
      path: "/js/clients-projects.js",
      type: "script",
      views: ["clients", "projects", "workbench"],
    },
  ],
  dashboard: [
    {
      id: "project-summary",
      label: "Project Summary",
      description: "Framework project/client hub data for dashboard reporting shortcuts.",
      renderer: "project-summary",
      moduleId: "client-projects",
      requiredWorkspaceCapabilities: ["projects", "clients_projects"],
      sortOrder: 10,
      terminology: {
        business: { label: "Client & Project Summary" },
        personal: { label: "Project Summary" },
      },
    },
  ],
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/clients", scope: "clients:read" },
    { method: "POST", path: "/api/v1/clients", scope: "clients:write" },
    { method: "GET", path: "/api/v1/clients/:clientId", scope: "clients:read" },
    { method: "PUT", path: "/api/v1/clients/:clientId", scope: "clients:write" },
    { method: "DELETE", path: "/api/v1/clients/:clientId", scope: "clients:write" },
    { method: "GET", path: "/api/v1/projects", scope: "projects:read" },
    { method: "POST", path: "/api/v1/projects", scope: "projects:write" },
    { method: "POST", path: "/api/v1/clients/:clientId/projects", scope: "projects:write" },
    { method: "GET", path: "/api/v1/projects/:projectId", scope: "projects:read" },
    { method: "PUT", path: "/api/v1/projects/:projectId", scope: "projects:write" },
    { method: "DELETE", path: "/api/v1/projects/:projectId", scope: "projects:write" },
  ],
  requiredPermissions: [
    "clients.manage",
    "projects.manage",
    "billing.manage",
  ],
  permissions: [
    {
      id: "clients.manage",
      moduleId: "client-projects",
      label: "Manage Clients",
      description: "Create, update, archive, and view clients.",
      resource: "clients",
      operation: "manage",
    },
    {
      id: "projects.manage",
      moduleId: "client-projects",
      label: "Manage Projects",
      description: "Create, update, archive, and view projects.",
      resource: "projects",
      operation: "manage",
    },
    {
      id: "billing.manage",
      moduleId: "client-projects",
      label: "Manage Billing Details",
      description: "Change billable status, rates, billing periods, and rounding.",
      resource: "billing",
      operation: "manage",
    },
  ],
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ["clients.manage", "projects.manage", "billing.manage"] },
    { roleId: "workspace_admin", permissions: ["clients.manage", "projects.manage", "billing.manage"] },
    { roleId: "client_admin", permissions: ["clients.manage", "projects.manage", "billing.manage"] },
    { roleId: "project_admin", permissions: ["projects.manage", "billing.manage"] },
  ],
  resourceDefinitions: [
    {
      key: "clients",
      moduleId: "client-projects",
      label: "Clients",
      operations: ["read", "create", "update", "archive", "restore", "manage"],
    },
    {
      key: "projects",
      moduleId: "client-projects",
      label: "Projects",
      operations: ["read", "create", "update", "archive", "restore", "manage"],
    },
    {
      key: "billing",
      moduleId: "client-projects",
      label: "Billing",
      operations: ["read", "update", "manage"],
    },
  ],
  auditRecordTypes: [
    {
      recordType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records and client lifecycle audit history.",
    },
    {
      recordType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records and project lifecycle audit history.",
    },
  ],
  taggableTypes: [
    {
      targetType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records that can receive workspace tags.",
      tableName: "clients",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      requiredReadPermission: "clients.manage",
      requiredTagPermission: "tags.assign",
      requiredModules: ["client-projects"],
    },
    {
      targetType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records that can receive workspace tags.",
      tableName: "projects",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      clientField: "client_id",
      requiredReadPermission: "projects.manage",
      requiredTagPermission: "tags.assign",
      requiredModules: ["client-projects"],
    },
  ],
  attachableTypes: [
    {
      targetType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records that can receive framework-managed file attachments.",
      tableName: "clients",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      requiredReadPermission: "clients.manage",
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.removed"],
      requiredModules: ["client-projects"],
      workspaceTypes: ["business"],
    },
    {
      targetType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records that can receive framework-managed file attachments.",
      tableName: "projects",
      idField: "id",
      labelField: "name",
      workspaceField: "workspace_id",
      clientField: "client_id",
      requiredReadPermission: "projects.manage",
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "presentation", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.removed"],
      requiredModules: ["client-projects"],
    },
  ],
  tagPropagation: [
    {
      id: "client-projects.client-parent-to-child",
      sourceModuleId: "client-projects",
      sourceTargetType: "client",
      targetModuleId: "client-projects",
      targetType: "client",
      relationshipResolver: "client-projects.client-children",
      workspaceField: "workspace_id",
      sourceReadPermission: "clients.manage",
      targetReadPermission: "clients.manage",
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
    {
      id: "client-projects.client-to-project",
      sourceModuleId: "client-projects",
      sourceTargetType: "client",
      targetModuleId: "client-projects",
      targetType: "project",
      relationshipResolver: "client-projects.client-projects",
      workspaceField: "workspace_id",
      sourceReadPermission: "clients.manage",
      targetReadPermission: "projects.manage",
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
    {
      id: "client-projects.project-parent-to-child",
      sourceModuleId: "client-projects",
      sourceTargetType: "project",
      targetModuleId: "client-projects",
      targetType: "project",
      relationshipResolver: "client-projects.project-children",
      workspaceField: "workspace_id",
      sourceReadPermission: "projects.manage",
      targetReadPermission: "projects.manage",
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
  ],
  searchableTypes: [
    {
      recordType: "client",
      moduleId: "client-projects",
      label: "Client",
      description: "Client records searchable by name, billing contact context, and tags.",
      idField: "id",
      titleField: "name",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      requiredReadPermission: "clients.manage",
      indexer: "client-projects.clients",
      requiredModules: ["client-projects"],
      tagsTextField: "tags_text",
      recordStatusField: "search_status",
      sourceLabel: "Client",
    },
    {
      recordType: "project",
      moduleId: "client-projects",
      label: "Project",
      description: "Project records searchable by name, client/parent project context, defaults, and tags.",
      idField: "id",
      titleField: "name",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      clientField: "client_id",
      requiredReadPermission: "projects.manage",
      indexer: "client-projects.projects",
      requiredModules: ["client-projects"],
      tagsTextField: "tags_text",
      recordStatusField: "search_status",
      sourceLabel: "Project",
    },
  ],
  apiScopes: [
    {
      id: "clients:read",
      moduleId: "client-projects",
      label: "Read Clients",
      description: "Read client records through the public API.",
      access: "read",
      workspaceTypes: ["business"],
    },
    {
      id: "clients:write",
      moduleId: "client-projects",
      label: "Write Clients",
      description: "Create, update, and archive client records through the public API.",
      access: "write",
      workspaceTypes: ["business"],
    },
    {
      id: "projects:read",
      moduleId: "client-projects",
      label: "Read Projects",
      description: "Read project records through the public API.",
      access: "read",
    },
    {
      id: "projects:write",
      moduleId: "client-projects",
      label: "Write Projects",
      description: "Create, update, and archive project records through the public API.",
      access: "write",
    },
  ],
  settings: [
    {
      id: "clientProjectsEnabled",
      label: "Projects",
      type: "boolean",
      moduleStatus: true,
      description: "Required project and workspace context module.",
      terminology: {
        business: { label: "Clients & Projects" },
        personal: { label: "Projects" },
        family: { label: "Projects" },
      },
    },
  ],
  workbench: [],
  timerSources: [],
  workItemSources: [],
  workspaceCapabilityRequirements: ["clients_projects", "projects"],
};

export { clientProjectsModule };
