import {
  NOTE_AUDIT_RECORD_TYPES,
  NOTE_EVENT_TYPES,
  NOTE_PERMISSIONS,
  NOTE_RESOURCE_DEFINITION,
} from "./access-policy.js";
import { notesRoutes } from "./notes.routes.js";
import { registerNotesSearchIndexers } from "./search-indexers.js";

registerNotesSearchIndexers();

function noteNotificationTitle({ event }) {
  return event.new_value?.title || event.previous_value?.title || event.metadata?.title || event.record_id || "Note";
}

const NOTE_PERMISSION_DEFINITIONS = [
  {
    id: NOTE_PERMISSIONS.VIEW,
    label: "View Notes",
    description: "View notes in an authorized workspace, client, project, task, ticket, or user scope.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_ALL,
    label: "View All Notes",
    description: "View all non-secure notes in an authorized workspace scope.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_PRIVATE,
    label: "View Private Notes",
    description: "View private notes in authorized scopes.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_SECURE,
    label: "View Secure Notes",
    description: "View secure note metadata and decrypted content when secure-note storage permits it.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.CREATE,
    label: "Create Notes",
    description: "Create notes in authorized Library and linked-record scopes.",
    operation: "create",
  },
  {
    id: NOTE_PERMISSIONS.UPDATE,
    label: "Update Notes",
    description: "Update note title, body, metadata, and linked context in authorized scopes.",
    operation: "update",
  },
  {
    id: NOTE_PERMISSIONS.UPDATE_SECURE,
    label: "Update Secure Notes",
    description: "Update secure notes when secure-note storage permits it.",
    operation: "update",
  },
  {
    id: NOTE_PERMISSIONS.ARCHIVE,
    label: "Archive Notes",
    description: "Archive notes while preserving their original Library bucket.",
    operation: "archive",
  },
  {
    id: NOTE_PERMISSIONS.RESTORE,
    label: "Restore Notes",
    description: "Restore archived notes to their previous Library bucket.",
    operation: "restore",
  },
  {
    id: NOTE_PERMISSIONS.DELETE,
    label: "Delete Notes",
    description: "Soft-delete notes where allowed.",
    operation: "delete",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_HISTORY,
    label: "View Note History",
    description: "View note revision history and user-friendly note changelog entries.",
    operation: "view_history",
  },
  {
    id: NOTE_PERMISSIONS.RESTORE_REVISION,
    label: "Restore Note Revisions",
    description: "Restore earlier note revisions where edit and history access allow it.",
    operation: "restore_revision",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_LINKS,
    label: "Manage Note Links",
    description: "Link and unlink notes to authorized workspace records.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_LIBRARY,
    label: "Manage Notes Library",
    description: "Manage Library buckets and Library collections without bypassing note access rules.",
    operation: "manage_library",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_SETTINGS,
    label: "Manage Notes Settings",
    description: "Manage workspace-level Notes settings.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.PUBLISH_CLIENT_VISIBLE,
    label: "Publish Client-Visible Notes",
    description: "Expose permitted notes to authorized client-visible surfaces when those surfaces exist.",
    operation: "manage",
  },
].map((permission) => ({
  ...permission,
  moduleId: "notes",
  resource: "notes",
}));

const ALL_NOTE_PERMISSION_IDS = NOTE_PERMISSION_DEFINITIONS.map((permission) => permission.id);
const INTERNAL_NOTE_PERMISSION_IDS = [
  NOTE_PERMISSIONS.VIEW,
  NOTE_PERMISSIONS.CREATE,
  NOTE_PERMISSIONS.UPDATE,
  NOTE_PERMISSIONS.ARCHIVE,
  NOTE_PERMISSIONS.RESTORE,
  NOTE_PERMISSIONS.VIEW_HISTORY,
  NOTE_PERMISSIONS.MANAGE_LINKS,
  NOTE_PERMISSIONS.MANAGE_LIBRARY,
];

const notesModule = {
  id: "notes",
  name: "Notes",
  displayName: "Notes",
  description: "Internal working notes organized by Library buckets and linked workspace records.",
  terminology: {
    default: {
      label: "Notes",
      singular: "Note",
      plural: "Notes",
      navigationLabel: "Notes",
      createButton: "Create Note",
      emptyState: "No notes found.",
    },
  },
  category: "core-workflow",
  version: "0.33.1.6",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [notesRoutes],
  publicApiRoutes: [],
  migrationsDir: new URL("./migrations/", import.meta.url),
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    {
      id: "notes",
      label: "Notes",
      href: "notes.html",
      parent: "projects.html",
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      requiresEnabledModules: ["notes"],
    },
  ],
  protectedViews: [
    {
      id: "notes",
      path: "/notes.html",
      moduleId: "notes",
      file: "notes.html",
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      allowDisabledRead: true,
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "notes-editor-helper",
      moduleId: "notes",
      path: "/js/shared/notes-editor.js",
      type: "script",
      views: ["notes"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
    {
      id: "notes-script",
      moduleId: "notes",
      path: "/js/notes.js",
      type: "script",
      views: ["notes"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
  ],
  dashboard: [],
  workbench: [],
  reporting: [],
  settings: [
    {
      id: "notesEnabled",
      label: "Notes",
      type: "boolean",
      moduleStatus: true,
    },
  ],
  requiredPermissions: ALL_NOTE_PERMISSION_IDS,
  permissions: NOTE_PERMISSION_DEFINITIONS,
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ALL_NOTE_PERMISSION_IDS },
    { roleId: "workspace_admin", permissions: ALL_NOTE_PERMISSION_IDS },
    { roleId: "client_admin", permissions: INTERNAL_NOTE_PERMISSION_IDS },
    { roleId: "project_admin", permissions: INTERNAL_NOTE_PERMISSION_IDS },
    { roleId: "client_user", permissions: [NOTE_PERMISSIONS.VIEW, NOTE_PERMISSIONS.CREATE, NOTE_PERMISSIONS.UPDATE, NOTE_PERMISSIONS.MANAGE_LINKS] },
    { roleId: "project_user", permissions: [NOTE_PERMISSIONS.VIEW, NOTE_PERMISSIONS.CREATE, NOTE_PERMISSIONS.UPDATE, NOTE_PERMISSIONS.MANAGE_LINKS] },
    { roleId: "client_external_user", permissions: [] },
  ],
  resourceDefinitions: [NOTE_RESOURCE_DEFINITION],
  auditRecordTypes: NOTE_AUDIT_RECORD_TYPES,
  publicApiEndpoints: [],
  apiScopes: [],
  eventTypes: NOTE_EVENT_TYPES,
  eventSummaries: [
    {
      event: "note.updated",
      moduleId: "notes",
      activity: {
        label: "Note Updated",
        summary: ({ event }) => `Updated note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}" was updated.`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
  ],
  hooks: { events: [] },
  timerSources: [],
  workItemSources: [],
  taggableTypes: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Note records that can receive workspace tags.",
      tableName: "notes",
      idField: "note_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredTagPermission: "tags.assign",
      requiredModules: ["notes"],
    },
  ],
  tagPropagation: [],
  searchableTypes: [
    {
      recordType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Notes searchable by title, safe body text, Library bucket, linked context, and tags.",
      idField: "note_id",
      titleField: "title",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      indexer: "notes.records",
      requiredModules: ["notes"],
      tagsTextField: "tags_text",
      visibilityField: "visibility",
      recordStatusField: "search_status",
      sourceLabel: "Notes",
    },
  ],
  attachableTypes: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Note records that can receive framework-managed file attachments.",
      tableName: "notes",
      idField: "note_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "presentation", "text", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.removed"],
      requiredModules: ["notes"],
    },
  ],
  notificationEvents: [
    {
      id: "note.updated",
      moduleId: "notes",
      label: "Note Updated",
      description: "Notifies a note owner when another user updates their non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
    },
  ],
  help: {
    sections: [
      {
        id: "notes.overview",
        moduleId: "notes",
        title: "Notes",
        description: "Current Notes behavior for Library buckets, linked records, Markdown, revisions, and attachments.",
        sortOrder: 120,
        audience: "user",
        tags: ["notes", "library"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
    ],
    articles: [
      {
        id: "notes.basics",
        slug: "notes-basics",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes Basics",
        summary: "Create internal workspace notes and connect them to the records they describe.",
        body: "Notes are internal working records that can stand alone in the workspace Library or link to clients, projects, tasks, tickets, and users.\n\nA note has a title, Markdown body, Library bucket, status, visibility, owner, optional linked context, tags, files, and revision history. Notes use the same workspace permissions and module-state rules as the rest of Longtail Forge.",
        sortOrder: 10,
        audience: "user",
        tags: ["notes", "basics"],
        relatedArticleIds: ["notes.library", "notes.markdown-links-revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.library",
        slug: "notes-library",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Library Buckets",
        summary: "Use Active Work, Ongoing Areas, Reference Library, and Archive to keep notes organized.",
        body: "The Notes Library groups notes by current purpose.\n\nActive Work is for notes tied to work in progress. Ongoing Areas is for durable areas that stay active over time. Reference Library is for retained knowledge and supporting material. Archive keeps completed notes available for historical lookup while separating them from active Library counts.\n\nLibrary bucket counts and search filters only expose notes the current user can read.",
        sortOrder: 20,
        audience: "user",
        tags: ["notes", "library", "archive"],
        relatedArticleIds: ["notes.search", "notes.basics"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.markdown-links-revisions",
        slug: "notes-markdown-links-revisions",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Markdown, Links, and Revisions",
        summary: "Write safe Markdown, link notes to workspace records, and review revision history.",
        body: "Note bodies support safe Markdown for headings, lists, links, and structured text. Unsafe markup is rejected before it is saved.\n\nLinked records connect a note to its workspace context without bypassing permissions. If a user cannot read the linked context, the note stays hidden from that user.\n\nRevision history records meaningful note changes. Users with note history permissions can review revisions and restore an earlier version.",
        sortOrder: 30,
        audience: "user",
        tags: ["notes", "markdown", "links", "revisions"],
        relatedArticleIds: ["notes.attachments-search"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.attachments-search",
        slug: "notes-attachments-search",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes, Files, and Search",
        summary: "Attach files to notes and find non-secure notes through workspace search.",
        body: "Notes can use framework-managed file attachments when the Files module and file permissions allow it. Attachment visibility follows the file rules for the note record.\n\nWorkspace search indexes non-secure, non-private notes by title, safe body text, excerpt, Library bucket, readable linked context, and tags. Archived notes stay searchable through the existing archived status filter. Secure notes are excluded from search results.",
        sortOrder: 40,
        audience: "user",
        tags: ["notes", "files", "search"],
        relatedArticleIds: ["notes.library", "notes.markdown-links-revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
    ],
  },
  frameworkDependencies: [
    "module-access",
    "permissions-service",
    "workspace-settings",
  ],
  moduleDependencies: [],
  workspaceCapabilityRequirements: [],
};

export { notesModule };
