import {
  NOTE_AUDIT_RECORD_TYPES,
  NOTE_EVENT_TYPES,
  NOTE_PERMISSIONS,
  NOTE_RESOURCE_DEFINITION,
} from "./access-policy.js";
import { notesRoutes } from "./notes.routes.js";
import { registerNotesSearchIndexers } from "./search-indexers.js";

registerNotesSearchIndexers();

function noteNotificationTitle({ event }) {
  return event.new_value?.title || event.previous_value?.title || event.metadata?.title || event.record_id || "Note";
}

const NOTE_PERMISSION_DEFINITIONS = [
  {
    id: NOTE_PERMISSIONS.VIEW,
    label: "View Notes",
    description: "View notes in an authorized workspace, client, project, task, ticket, or user scope.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_ALL,
    label: "View All Notes",
    description: "View all non-secure notes in an authorized workspace scope.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_PRIVATE,
    label: "View Private Notes",
    description: "View private notes in authorized scopes.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.CREATE,
    label: "Create Notes",
    description: "Create notes in authorized Library and linked-record scopes.",
    operation: "create",
  },
  {
    id: NOTE_PERMISSIONS.UPDATE,
    label: "Update Notes",
    description: "Update note title, body, metadata, and linked context in authorized scopes.",
    operation: "update",
  },
  {
    id: NOTE_PERMISSIONS.ARCHIVE,
    label: "Archive Notes",
    description: "Archive notes while preserving their original Library bucket.",
    operation: "archive",
  },
  {
    id: NOTE_PERMISSIONS.RESTORE,
    label: "Restore Notes",
    description: "Restore archived notes to their previous Library bucket.",
    operation: "restore",
  },
  {
    id: NOTE_PERMISSIONS.DELETE,
    label: "Delete Notes",
    description: "Soft-delete notes where allowed.",
    operation: "delete",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_HISTORY,
    label: "View Note History",
    description: "View note revision history and user-friendly note changelog entries.",
    operation: "view_history",
  },
  {
    id: NOTE_PERMISSIONS.RESTORE_REVISION,
    label: "Restore Note Revisions",
    description: "Restore earlier note revisions where edit and history access allow it.",
    operation: "restore_revision",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_LINKS,
    label: "Manage Note Links",
    description: "Link and unlink notes to authorized workspace records.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_LIBRARY,
    label: "Manage Notes Library",
    description: "Manage Library buckets and Library collections without bypassing note access rules.",
    operation: "manage_library",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_SETTINGS,
    label: "Manage Notes Settings",
    description: "Manage workspace-level Notes settings.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.PUBLISH_CLIENT_VISIBLE,
    label: "Publish Client-Visible Notes",
    description: "Expose permitted notes to authorized client-visible surfaces when those surfaces exist.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_CREATE,
    label: "Create Secure Notes",
    description: "Create encrypted secure notes when secure-note storage is configured.",
    operation: "create",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_VIEW,
    label: "View Secure Notes",
    description: "View secure note metadata and decrypted secure-note bodies when allowed.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_UPDATE,
    label: "Update Secure Notes",
    description: "Update encrypted secure-note bodies and metadata when allowed.",
    operation: "update",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_ARCHIVE,
    label: "Archive Secure Notes",
    description: "Archive secure notes without exposing secure body content.",
    operation: "archive",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_RESTORE,
    label: "Restore Secure Notes",
    description: "Restore archived secure notes without exposing secure body content.",
    operation: "restore",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_DELETE,
    label: "Delete Secure Notes",
    description: "Soft-delete secure notes without exposing secure body content.",
    operation: "delete",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_VIEW_HISTORY,
    label: "View Secure Note History",
    description: "View secure note revision metadata and decrypt secure revisions when allowed.",
    operation: "view_history",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_MANAGE,
    label: "Manage Secure Notes",
    description: "Administrative secure-note access for users with explicit secure-note responsibility.",
    operation: "manage",
  },
].map((permission) => ({
  ...permission,
  moduleId: "notes",
  resource: "notes",
}));

const ALL_NOTE_PERMISSION_IDS = NOTE_PERMISSION_DEFINITIONS.map((permission) => permission.id);
const INTERNAL_NOTE_PERMISSION_IDS = [
  NOTE_PERMISSIONS.VIEW,
  NOTE_PERMISSIONS.CREATE,
  NOTE_PERMISSIONS.UPDATE,
  NOTE_PERMISSIONS.ARCHIVE,
  NOTE_PERMISSIONS.RESTORE,
  NOTE_PERMISSIONS.VIEW_HISTORY,
  NOTE_PERMISSIONS.MANAGE_LINKS,
  NOTE_PERMISSIONS.MANAGE_LIBRARY,
];

const notesModule = {
  id: "notes",
  name: "Notes",
  displayName: "Notes",
  description: "Internal working notes organized by Library buckets and linked workspace records.",
  terminology: {
    default: {
      label: "Notes",
      singular: "Note",
      plural: "Notes",
      navigationLabel: "Notes",
      createButton: "Create Note",
      emptyState: "No notes found.",
    },
  },
  category: "core-workflow",
  version: "0.33.5.8.3",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [notesRoutes],
  publicApiRoutes: [],
  migrationsDir: new URL("./migrations/", import.meta.url),
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    {
      id: "notes",
      label: "Notes",
      href: "notes.html",
      parent: "projects.html",
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      requiresEnabledModules: ["notes"],
    },
  ],
  protectedViews: [
    {
      id: "notes",
      path: "/notes.html",
      moduleId: "notes",
      file: "notes.html",
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      allowDisabledRead: true,
    },
  ],
  publicViews: [],
  browserAssets: [
    {
      id: "notes-editor-helper",
      moduleId: "notes",
      path: "/js/shared/notes-editor.js",
      type: "script",
      views: ["notes"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
    {
      id: "notes-linked-panel-helper",
      moduleId: "notes",
      path: "/js/shared/notes-linked-panel.js",
      type: "script",
      views: ["tasks", "projects", "clients", "lists", "files"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
    {
      id: "notes-script",
      moduleId: "notes",
      path: "/js/notes.js",
      type: "script",
      views: ["notes"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
  ],
  dashboard: [],
  workbench: [],
  reporting: [],
  settings: [
    {
      id: "notesEnabled",
      label: "Notes",
      type: "boolean",
      moduleStatus: true,
    },
  ],
  requiredPermissions: ALL_NOTE_PERMISSION_IDS,
  permissions: NOTE_PERMISSION_DEFINITIONS,
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ALL_NOTE_PERMISSION_IDS },
    { roleId: "workspace_admin", permissions: ALL_NOTE_PERMISSION_IDS },
    { roleId: "client_admin", permissions: INTERNAL_NOTE_PERMISSION_IDS },
    { roleId: "project_admin", permissions: INTERNAL_NOTE_PERMISSION_IDS },
    { roleId: "client_user", permissions: [NOTE_PERMISSIONS.VIEW, NOTE_PERMISSIONS.CREATE, NOTE_PERMISSIONS.UPDATE, NOTE_PERMISSIONS.MANAGE_LINKS] },
    { roleId: "project_user", permissions: [NOTE_PERMISSIONS.VIEW, NOTE_PERMISSIONS.CREATE, NOTE_PERMISSIONS.UPDATE, NOTE_PERMISSIONS.MANAGE_LINKS] },
    { roleId: "client_external_user", permissions: [] },
  ],
  resourceDefinitions: [NOTE_RESOURCE_DEFINITION],
  auditRecordTypes: NOTE_AUDIT_RECORD_TYPES,
  publicApiEndpoints: [],
  apiScopes: [],
  eventTypes: NOTE_EVENT_TYPES,
  eventSummaries: [
    {
      event: "note.updated",
      moduleId: "notes",
      activity: {
        label: "Note Updated",
        summary: ({ event }) => `Updated note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}" was updated.`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
  ],
  hooks: { events: [] },
  timerSources: [],
  workItemSources: [],
  taggableTypes: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Note records that can receive workspace tags.",
      tableName: "notes",
      idField: "note_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredTagPermission: "tags.assign",
      requiredModules: ["notes"],
    },
  ],
  tagPropagation: [],
  searchableTypes: [
    {
      recordType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Notes searchable by title, safe body text, Library bucket, linked context, and tags.",
      idField: "note_id",
      titleField: "title",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      indexer: "notes.records",
      requiredModules: ["notes"],
      tagsTextField: "tags_text",
      visibilityField: "visibility",
      recordStatusField: "search_status",
      sourceLabel: "Notes",
    },
  ],
  attachableTypes: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Note records that can receive framework-managed file attachments.",
      tableName: "notes",
      idField: "note_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "presentation", "text", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.removed"],
      requiredModules: ["notes"],
    },
  ],
  notificationEvents: [
    {
      id: "note.updated",
      moduleId: "notes",
      label: "Note Updated",
      description: "Notifies a note owner when another user updates their non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
    },
  ],
  help: {
    sections: [
      {
        id: "notes.overview",
        moduleId: "notes",
        title: "Notes",
        description: "Current Notes behavior for usage, Library buckets, collections, linked records, Markdown, revisions, secure notes, and files.",
        sortOrder: 120,
        audience: "user",
        tags: ["notes", "library"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
    ],
    articles: [
      {
        id: "notes.basics",
        slug: "notes-basics",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Using Notes",
        summary: "Create internal working notes and keep them organized without leaving the current workspace.",
        body: "Notes are internal working records. A note can stand alone in the Notes Library or link to a client, project, task, ticket, or user when that context helps explain the work.\n\nEach note has a title, Markdown body, Library bucket, status, visibility, owner, optional linked context, tags, files, and revision history. Notes follow the same module-state and permission checks as the rest of Longtail Forge, so a Library bucket, collection, tag, or linked record never grants access by itself.",
        sortOrder: 10,
        audience: "user",
        tags: ["notes", "basics"],
        relatedArticleIds: ["notes.library", "notes.collections", "notes.linking"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.library",
        slug: "notes-library",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes Library",
        summary: "Use the Notes Library to filter notes by current purpose and archived state.",
        body: "The Notes Library groups notes by current purpose. Active Work is for notes tied to work in progress. Ongoing Areas is for durable areas that stay active over time. Reference Library is for retained material. Archive keeps completed notes available for historical lookup while separating them from active Library counts.\n\nLibrary counts, collection counts, and search filters only expose notes the current user can read. Moving a note between active buckets may clear its collection when the old collection belongs to a different bucket.",
        sortOrder: 20,
        audience: "user",
        tags: ["notes", "library", "archive"],
        relatedArticleIds: ["notes.active-work", "notes.ongoing-areas", "notes.reference-library", "notes.archive"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.collections",
        slug: "notes-collections",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes Collections",
        summary: "Use collections as single-bucket folders for notes, not as permissions or record links.",
        body: "Collections organize notes inside one Library bucket. A collection can have child collections, and a note can belong to one current collection.\n\nCollections are classification metadata. They do not grant access, expose private or secure notes, replace linked clients or projects, or make a note visible to someone who cannot otherwise read it. Collection counts are permission-filtered, and archived collections stay out of the normal tree unless they are explicitly included.",
        sortOrder: 30,
        audience: "user",
        tags: ["notes", "collections", "library"],
        relatedArticleIds: ["notes.library", "notes.archive"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.active-work",
        slug: "notes-active-work",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Active Work",
        summary: "Keep notes for work in progress in Active Work.",
        body: "Active Work is the bucket for notes tied to current action, open tasks, active tickets, and short-term working context.\n\nTask or ticket context can suggest Active Work when a note is created, but the suggestion is only a starting point. The note still follows its visibility, owner, linked-record access, collection, secure-note, and permission rules.",
        sortOrder: 40,
        audience: "user",
        tags: ["notes", "active work", "library"],
        relatedArticleIds: ["notes.library", "notes.linking"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.ongoing-areas",
        slug: "notes-ongoing-areas",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Ongoing Areas",
        summary: "Keep durable responsibilities and recurring context in Ongoing Areas.",
        body: "Ongoing Areas is the bucket for durable responsibilities, standing clients, long-running projects, and reference that stays active over time.\n\nClient, project, or user context can suggest Ongoing Areas when a note is created. That suggestion does not change access: users still need the required note permissions and readable linked context.",
        sortOrder: 50,
        audience: "user",
        tags: ["notes", "ongoing areas", "library"],
        relatedArticleIds: ["notes.library", "notes.linking"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.reference-library",
        slug: "notes-reference-library",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Reference Library",
        summary: "Keep retained notes and supporting material in Reference Library.",
        body: "Reference Library is the bucket for retained notes, background material, policies, research, and other supporting context that is useful to keep but is not active work.\n\nStandalone notes default to Reference Library unless a different bucket is selected. Reference notes can still use collections, tags, links, revisions, and files when the current user has the right permissions.",
        sortOrder: 60,
        audience: "user",
        tags: ["notes", "reference library", "library"],
        relatedArticleIds: ["notes.library", "notes.collections"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.archive",
        slug: "notes-archive",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Archive",
        summary: "Move completed notes to Archive while preserving their original Library bucket.",
        body: "Archive is a read-mostly state for completed or historical notes. Archived notes keep their original Library bucket and collection so they can be restored without losing context.\n\nArchived notes are separated from active Library counts and normal edit flows. Restore a note before making normal content changes. Archived notes can remain discoverable through archived filters when the current user can read them.",
        sortOrder: 70,
        audience: "user",
        tags: ["notes", "archive", "library"],
        relatedArticleIds: ["notes.library", "notes.revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.markdown",
        slug: "notes-markdown",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Markdown",
        summary: "Write note bodies in safe Markdown.",
        body: "Note bodies use Markdown as the editable format. Headings, lists, links, and structured text are supported, while unsafe HTML and scriptable input are rejected before saving.\n\nWiki-style link text can be detected as note metadata, but detection does not auto-create notes and does not reveal private or secure notes to users who cannot read them.",
        sortOrder: 80,
        audience: "user",
        tags: ["notes", "markdown"],
        relatedArticleIds: ["notes.linking", "notes.revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.linking",
        slug: "notes-linking",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Note Linking",
        summary: "Connect notes to the records they describe without changing access rules.",
        body: "A note can link to workspace context such as a client, project, task, ticket, or user. Links make a note easier to find from the related work, but they do not grant access to the note or to the linked record.\n\nIf a user cannot read the linked context, the note is hidden from that user. Link creation and removal also check the current user's note and target-record access.",
        sortOrder: 90,
        audience: "user",
        tags: ["notes", "links"],
        relatedArticleIds: ["notes.basics", "notes.active-work", "notes.ongoing-areas"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.revisions",
        slug: "notes-revisions",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Note Revisions",
        summary: "Review meaningful note changes and restore earlier versions when allowed.",
        body: "Revision history records meaningful note changes after creation. Notes do not create an initial revision at creation time.\n\nUsers with note history permissions can review revisions and restore an earlier version. Restoring creates a new update and a new revision snapshot instead of rewriting history. Secure note revision lists are metadata-only unless secure-history access allows a dedicated decrypt read.",
        sortOrder: 100,
        audience: "user",
        tags: ["notes", "revisions", "history"],
        relatedArticleIds: ["notes.archive", "notes.secure-notes"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW_HISTORY],
      },
      {
        id: "notes.secure-notes",
        slug: "notes-secure-notes",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Secure Notes",
        summary: "Use secure notes for encrypted-at-rest body content with stricter access rules.",
        body: "Secure notes encrypt the note body at rest with application-managed envelope encryption. This protects database exposure, but it is not zero-knowledge because a configured app server can decrypt secure bodies after session and permission checks.\n\nSecure note titles are visible to users who can view note metadata. Do not put secrets in the title.\n\nOnly the owner and users with explicit secure-note permissions can access secure bodies. Normal note permissions, workspace membership, Library buckets, collections, linked records, tags, and file permissions do not grant secure body access. Secure notes are excluded from normal search, list previews, file attachments, client-visible controls, and ordinary note notification content.",
        sortOrder: 110,
        audience: "user",
        tags: ["notes", "secure notes"],
        relatedArticleIds: ["notes.basics", "notes.revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.attachments-search",
        slug: "notes-attachments-search",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes, Files, and Search",
        summary: "Attach files to notes and find non-secure notes through workspace search.",
        body: "Notes can use framework-managed file attachments when the Files module and file permissions allow it. Attachment visibility follows the file rules for the note record.\n\nWorkspace search indexes non-secure, non-private notes by title, safe body text, excerpt, Library bucket, readable linked context, and tags. Archived notes stay searchable through the existing archived status filter. Secure notes are excluded from search results.",
        sortOrder: 120,
        audience: "user",
        tags: ["notes", "files", "search"],
        relatedArticleIds: ["notes.library", "notes.secure-notes"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
    ],
  },
  frameworkDependencies: [
    "module-access",
    "permissions-service",
    "workspace-settings",
  ],
  moduleDependencies: [],
  workspaceCapabilityRequirements: [],
};

export { notesModule };
