import {
  NOTE_AUDIT_RECORD_TYPES,
  NOTE_EVENT_TYPES,
  NOTE_PERMISSIONS,
  NOTE_RESOURCE_DEFINITION,
} from "./access-policy.js";
import { notesPublicApiRoutes } from "./public-api.routes.js";
import { notesRoutes } from "./notes.routes.js";
import { registerNotesSearchIndexers } from "./search-indexers.js";
import { LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT } from "../../core/linked-context/provider-contract.js";

registerNotesSearchIndexers();

function noteNotificationTitle({ event }) {
  return event.new_value?.title || event.previous_value?.title || event.metadata?.title || event.record_id || "Note";
}

const NOTE_PERMISSION_DEFINITIONS = [
  {
    id: NOTE_PERMISSIONS.VIEW,
    label: "View Notes",
    description: "View notes in an authorized workspace, client, project, task, ticket, or user scope.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_ALL,
    label: "View All Notes",
    description: "View all non-secure notes in an authorized workspace scope.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_PRIVATE,
    label: "View Private Notes",
    description: "View private notes in authorized scopes.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.CREATE,
    label: "Create Notes",
    description: "Create notes in authorized Library and linked-record scopes.",
    operation: "create",
  },
  {
    id: NOTE_PERMISSIONS.UPDATE,
    label: "Update Notes",
    description: "Update note title, body, metadata, and linked context in authorized scopes.",
    operation: "update",
  },
  {
    id: NOTE_PERMISSIONS.ARCHIVE,
    label: "Archive Notes",
    description: "Archive notes while preserving their original Library bucket.",
    operation: "archive",
  },
  {
    id: NOTE_PERMISSIONS.RESTORE,
    label: "Restore Notes",
    description: "Restore archived notes to their previous Library bucket.",
    operation: "restore",
  },
  {
    id: NOTE_PERMISSIONS.DELETE,
    label: "Delete Notes",
    description: "Soft-delete notes where allowed.",
    operation: "delete",
  },
  {
    id: NOTE_PERMISSIONS.VIEW_HISTORY,
    label: "View Note History",
    description: "View note revision history and user-friendly note changelog entries.",
    operation: "view_history",
  },
  {
    id: NOTE_PERMISSIONS.RESTORE_REVISION,
    label: "Restore Note Revisions",
    description: "Restore earlier note revisions where edit and history access allow it.",
    operation: "restore_revision",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_LINKS,
    label: "Manage Note Links",
    description: "Link and unlink notes to authorized workspace records.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_LIBRARY,
    label: "Manage Notes Library",
    description: "Manage Library buckets and Library collections without bypassing note access rules.",
    operation: "manage_library",
  },
  {
    id: NOTE_PERMISSIONS.MANAGE_SETTINGS,
    label: "Manage Notes Settings",
    description: "Manage workspace-level Notes settings.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.PUBLISH_CLIENT_VISIBLE,
    label: "Publish Client-Visible Notes",
    description: "Expose permitted notes to authorized client-visible surfaces when those surfaces exist.",
    operation: "manage",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_CREATE,
    label: "Create Secure Notes",
    description: "Create encrypted secure notes when secure-note storage is configured.",
    operation: "create",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_VIEW,
    label: "View Secure Notes",
    description: "View secure note metadata and decrypted secure-note bodies when allowed.",
    operation: "read",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_UPDATE,
    label: "Update Secure Notes",
    description: "Update encrypted secure-note bodies and metadata when allowed.",
    operation: "update",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_ARCHIVE,
    label: "Archive Secure Notes",
    description: "Archive secure notes without exposing secure body content.",
    operation: "archive",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_RESTORE,
    label: "Restore Secure Notes",
    description: "Restore archived secure notes without exposing secure body content.",
    operation: "restore",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_DELETE,
    label: "Delete Secure Notes",
    description: "Soft-delete secure notes without exposing secure body content.",
    operation: "delete",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_VIEW_HISTORY,
    label: "View Secure Note History",
    description: "View secure note revision metadata and decrypt secure revisions when allowed.",
    operation: "view_history",
  },
  {
    id: NOTE_PERMISSIONS.SECURE_MANAGE,
    label: "Manage Secure Notes",
    description: "Administrative secure-note access for users with explicit secure-note responsibility.",
    operation: "manage",
  },
].map((permission) => ({
  ...permission,
  moduleId: "notes",
  resource: "notes",
}));

const ALL_NOTE_PERMISSION_IDS = NOTE_PERMISSION_DEFINITIONS.map((permission) => permission.id);
const INTERNAL_NOTE_PERMISSION_IDS = [
  NOTE_PERMISSIONS.VIEW,
  NOTE_PERMISSIONS.CREATE,
  NOTE_PERMISSIONS.UPDATE,
  NOTE_PERMISSIONS.ARCHIVE,
  NOTE_PERMISSIONS.RESTORE,
  NOTE_PERMISSIONS.VIEW_HISTORY,
  NOTE_PERMISSIONS.MANAGE_LINKS,
  NOTE_PERMISSIONS.MANAGE_LIBRARY,
];

const notesModule = {
  id: "notes",
  name: "Notes",
  displayName: "Notes",
  description: "Internal working notes organized by Library buckets and linked workspace records.",
  terminology: {
    default: {
      label: "Notes",
      singular: "Note",
      plural: "Notes",
      navigationLabel: "Notes",
      createButton: "Create Note",
      emptyState: "No notes found.",
    },
  },
  category: "core-workflow",
  version: "0.33.5.21.0.5",
  enabledByDefault: true,
  canDisable: true,
  historicalReadAccess: true,
  browserApiRoutes: [notesRoutes],
  publicApiRoutes: [notesPublicApiRoutes],
  migrationsDir: null,
  protectedViewsDir: new URL("../../../views/protected/", import.meta.url),
  browserAssetsDir: new URL("../../../public/js/", import.meta.url),
  seedHooks: [],
  repairHooks: [],
  navigation: [
    {
      id: "notes",
      label: "Notes",
      href: "notes.html",
      parent: "projects.html",
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      requiresEnabledModules: ["notes"],
    },
  ],
  protectedViews: [
    {
      id: "notes",
      path: "/notes.html",
      moduleId: "notes",
      file: "notes.html",
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      allowDisabledRead: true,
    },
  ],
  publicViews: [],
  viewSurfaces: [
    {
      id: "notes.workspace",
      moduleId: "notes",
      viewId: "notes",
      layout: "slide-out-sidebar",
      sidebarLabel: "Notes navigation",
      pageHeader: {
        title: "Notes",
        titleKey: "label",
        primaryAction: {
          id: "create-note",
          label: "Create Note",
          labelKey: "createButton",
          role: "primary",
          behavior: "notes.create",
          requiredPermissions: [NOTE_PERMISSIONS.CREATE],
        },
      },
      sidebarPanels: [
        {
          id: "notes-filters",
          type: "filters",
          title: "Filters",
          open: false,
          className: "notes-filters-panel",
        },
        {
          id: "notes-library",
          type: "navigation",
          title: "Library",
          behavior: "notes.sidebar.library",
          open: true,
          className: "notes-library-panel view-collapsible-index--unscrolled",
          ariaLabel: "Notes Library",
        },
        {
          id: "notes-list",
          type: "index",
          title: "Notes List",
          open: true,
          className: "notes-index-panel",
          footer: {
            id: "notes-list-footer",
            behavior: "notes.sidebar.notes-list-footer",
          },
        },
      ],
      filters: [
        {
          id: "status-filter",
          field: "status",
          type: "select",
          label: "Status",
          default: "active",
          options: [["active", "Active", true], ["pinned", "Pinned"], ["archived", "Archived"], ["all", "All visible"]],
        },
        {
          id: "visibility-filter",
          field: "visibility",
          type: "select",
          label: "Visibility",
          default: "all",
          options: [["all", "All visible", true], ["internal", "Internal"], ["private", "Private"], ["workspace", "Workspace"], ["client_visible", "Client Visible"]],
        },
        {
          id: "security-filter",
          field: "security",
          type: "select",
          label: "Security",
          default: "all",
          options: [["all", "All", true], ["normal", "Normal"], ["secure", "Secure"]],
        },
        {
          id: "type-filter",
          field: "noteType",
          type: "select",
          label: "Note Kind",
          default: "all",
          options: [["all", "All kinds", true], ["general", "General"], ["meeting", "Meeting"], ["research", "Research"], ["decision", "Decision"], ["procedure", "Procedure"], ["reference", "Reference"], ["idea", "Idea"], ["log", "Log"]],
        },
        { id: "context-filter", field: "context", type: "search", label: "Context" },
        { id: "owner-filter", field: "owner", type: "search", label: "Owner" },
        { id: "tags-filter", field: "tags", type: "search", label: "Tags", optionsSource: "notes.filters.tags" },
        { id: "updated-filter", field: "updatedSince", type: "date", label: "Updated Since" },
      ],
      indexPanel: {
        title: "Notes",
        titleKey: "plural",
        itemTitleField: "title",
        itemSubtitleField: "excerpt",
        itemMetaFields: ["library", "updatedAt"],
        emptyState: {
          title: "No notes",
          message: "No notes match the current filters.",
        },
      },
      detail: {
        header: {
          titleField: "title",
          metaField: "library",
          badges: [{ field: "status" }, { field: "visibility" }, { field: "security" }],
        },
        actionStrip: {
          label: "Note actions",
          actions: [
            { id: "edit-note", label: "Edit", role: "secondary", behavior: "notes.workflow.edit", requiredPermissions: [NOTE_PERMISSIONS.UPDATE] },
            { id: "archive-note", label: "Archive", role: "secondary", behavior: "notes.workflow.archive", requiredPermissions: [NOTE_PERMISSIONS.ARCHIVE] },
            { id: "restore-note", label: "Restore", role: "secondary", behavior: "notes.workflow.restore", requiredPermissions: [NOTE_PERMISSIONS.RESTORE] },
          ],
        },
        summaryPanels: [
          {
            title: "Context",
            description: "Linked workspace context for this note.",
          },
        ],
        linkedRecords: {
          title: "Linked Context",
          recordsField: "links",
          emptyState: { message: "No linked context." },
          fields: [
            { field: "target_type", type: "select", label: "Type", behavior: "notes.link.target-type" },
            { field: "target_search", type: "search", label: "Search records", placeholder: "Search records", autocomplete: "off", behavior: "notes.link.search" },
            { field: "target_results", type: "select", label: "Record", required: true, behavior: "notes.link.results" },
          ],
          actions: [
            { id: "add-link", label: "Add Link", role: "primary", behavior: "notes.link.add", requiredPermissions: [NOTE_PERMISSIONS.MANAGE_LINKS] },
            { id: "remove-link", label: "Remove", role: "destructive", behavior: "notes.link.remove", requiredPermissions: [NOTE_PERMISSIONS.MANAGE_LINKS] },
          ],
        },
        emptyState: {
          title: "Select a note",
          message: "Select a note to read its details.",
        },
      },
      modals: [
        {
          id: "note-editor",
          title: "Note",
          fields: [
            { id: "note-title", field: "title", type: "text", label: "Title", required: true },
            { id: "note-library", field: "library", type: "select", label: "Library", options: [["active_work", "Active Work"], ["ongoing_area", "Ongoing Areas"], ["reference", "Reference Library"]] },
            { id: "note-collection", field: "collection", type: "select", label: "Collection", options: [["", "Uncategorized"]] },
            { id: "note-kind", field: "noteType", type: "select", label: "Note Kind", options: [["general", "General"], ["meeting", "Meeting"], ["research", "Research"], ["decision", "Decision"], ["procedure", "Procedure"], ["reference", "Reference"], ["idea", "Idea"], ["log", "Log"]] },
            { id: "note-visibility", field: "visibility", type: "select", label: "Visibility", options: [["internal", "Internal"], ["private", "Private"], ["workspace", "Workspace"], ["client_visible", "Client Visible"]] },
            { id: "note-security", field: "security", type: "select", label: "Security", options: [["normal", "Normal"], ["secure", "Secure"]] },
          ],
          footerActions: [
            { id: "cancel-note", label: "Cancel", role: "secondary", behavior: "notes.editor.cancel" },
            { id: "save-note", label: "Save Note", role: "primary", behavior: "notes.editor.save" },
          ],
        },
        {
          id: "note-collection",
          title: "Collection",
          fields: [
            { id: "collection-name", field: "title", type: "text", label: "Name", required: true },
            { id: "collection-library", field: "library", type: "select", label: "Library", options: [["active_work", "Active Work"], ["ongoing_area", "Ongoing Areas"], ["reference", "Reference Library"]] },
            { id: "collection-parent", field: "parent", type: "select", label: "Parent", options: [["", "Root collection"]] },
          ],
          footerActions: [
            { id: "cancel-collection", label: "Cancel", role: "secondary", behavior: "notes.collection.cancel" },
            { id: "save-collection", label: "Save Collection", role: "primary", behavior: "notes.collection.save" },
          ],
        },
      ],
      dataSource: {
        route: "/api/notes",
        method: "GET",
        fieldBindings: {
          id: "note_id",
          title: "title",
          excerpt: "body_excerpt",
          status: "status",
          visibility: "visibility",
          security: "security_mode",
          library: "library_bucket",
          noteType: "note_type",
          updatedAt: "updated_at",
        },
      },
    },
  ],
  browserAssets: [
    {
      id: "notes-editor-helper",
      moduleId: "notes",
      path: "/js/shared/notes-editor.js",
      type: "script",
      views: ["notes"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
    {
      id: "notes-linked-panel-helper",
      moduleId: "notes",
      path: "/js/shared/notes-linked-panel.js",
      type: "script",
      views: ["tasks", "projects", "clients", "lists", "files"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
    {
      id: "notes-script",
      moduleId: "notes",
      path: "/js/notes.js",
      type: "script",
      views: ["notes"],
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
    },
  ],
  dashboard: [],
  workbench: [],
  reporting: [],
  settings: [
    {
      id: "notesEnabled",
      label: "Notes",
      type: "boolean",
      moduleStatus: true,
    },
  ],
  requiredPermissions: ALL_NOTE_PERMISSION_IDS,
  permissions: NOTE_PERMISSION_DEFINITIONS,
  defaultRolePermissions: [
    { roleId: "super_admin", permissions: ALL_NOTE_PERMISSION_IDS },
    { roleId: "workspace_admin", permissions: ALL_NOTE_PERMISSION_IDS },
    { roleId: "client_admin", permissions: INTERNAL_NOTE_PERMISSION_IDS },
    { roleId: "project_admin", permissions: INTERNAL_NOTE_PERMISSION_IDS },
    { roleId: "client_user", permissions: [NOTE_PERMISSIONS.VIEW, NOTE_PERMISSIONS.CREATE, NOTE_PERMISSIONS.UPDATE, NOTE_PERMISSIONS.MANAGE_LINKS] },
    { roleId: "project_user", permissions: [NOTE_PERMISSIONS.VIEW, NOTE_PERMISSIONS.CREATE, NOTE_PERMISSIONS.UPDATE, NOTE_PERMISSIONS.MANAGE_LINKS] },
    { roleId: "client_external_user", permissions: [] },
  ],
  resourceDefinitions: [NOTE_RESOURCE_DEFINITION],
  auditRecordTypes: NOTE_AUDIT_RECORD_TYPES,
  publicApiEndpoints: [
    { method: "GET", path: "/api/v1/notes", scope: "notes:read" },
    { method: "GET", path: "/api/v1/notes/:noteId", scope: "notes:read" },
  ],
  apiScopes: [
    {
      id: "notes:read",
      moduleId: "notes",
      label: "Read Notes",
      description: "Read non-secure notes through the public API.",
      access: "read",
    },
  ],
  eventTypes: NOTE_EVENT_TYPES,
  eventSummaries: [
    {
      event: "note.updated",
      moduleId: "notes",
      activity: {
        label: "Note Updated",
        summary: ({ event }) => `Updated note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}" was updated.`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
    {
      event: "note.archived",
      moduleId: "notes",
      activity: {
        label: "Note Archived",
        summary: ({ event }) => `Archived note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}" was archived.`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
    {
      event: "note.restored",
      moduleId: "notes",
      activity: {
        label: "Note Restored",
        summary: ({ event }) => `Restored note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}" was restored.`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
    {
      event: "note.linked",
      moduleId: "notes",
      activity: {
        label: "Note Linked",
        summary: ({ event }) => `Linked context changed for note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Linked context changed for note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
    {
      event: "note.unlinked",
      moduleId: "notes",
      activity: {
        label: "Note Unlinked",
        summary: ({ event }) => `Linked context changed for note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
      },
      notification: {
        title: noteNotificationTitle,
        body: ({ event }) => `Linked context changed for note "${event.new_value?.title || event.previous_value?.title || event.record_id || "Note"}".`,
        url: ({ event }) => `notes.html?note=${encodeURIComponent(event.record_id || "")}`,
        recipientHints: [],
      },
    },
  ],
  hooks: { events: [] },
  timerSources: [],
  workItemSources: [],
  taggableTypes: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Note records that can receive workspace tags.",
      tableName: "notes",
      idField: "note_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredTagPermission: "tags.assign",
      requiredModules: ["notes"],
    },
  ],
  tagPropagation: [
    {
      id: "notes.client-to-note",
      sourceModuleId: "client-projects",
      sourceTargetType: "client",
      targetModuleId: "notes",
      targetType: "note",
      relationshipResolver: "notes.client-notes",
      workspaceField: "workspace_id",
      sourceReadPermission: "clients.manage",
      targetReadPermission: NOTE_PERMISSIONS.VIEW,
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "notes", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
    {
      id: "notes.project-to-note",
      sourceModuleId: "client-projects",
      sourceTargetType: "project",
      targetModuleId: "notes",
      targetType: "note",
      relationshipResolver: "notes.project-notes",
      workspaceField: "workspace_id",
      sourceReadPermission: "projects.manage",
      targetReadPermission: NOTE_PERMISSIONS.VIEW,
      targetTagPermission: "tags.assign",
      requiredModules: ["client-projects", "notes", "tags"],
      propagateOnParentChange: true,
      propagateOnRelationshipChange: true,
    },
  ],
  searchableTypes: [
    {
      recordType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Notes searchable by title, safe body text, Library bucket, linked context, and tags.",
      idField: "note_id",
      titleField: "title",
      summaryField: "summary",
      bodyFields: ["body"],
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      indexer: "notes.records",
      requiredModules: ["notes"],
      tagsTextField: "tags_text",
      visibilityField: "visibility",
      recordStatusField: "search_status",
      sourceLabel: "Notes",
    },
  ],
  attachableTypes: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Note records that can receive framework-managed file attachments.",
      tableName: "notes",
      idField: "note_id",
      labelField: "title",
      workspaceField: "workspace_id",
      clientField: "client_id",
      projectField: "project_id",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredAttachPermission: "files.upload",
      requiredRemovePermission: "files.delete",
      allowedFileCategories: ["document", "image", "pdf", "spreadsheet", "presentation", "text", "other"],
      allowedVisibilityValues: ["private", "workspace", "client"],
      lifecycleEvents: ["file.attachment.created", "file.attachment.context_updated", "file.attachment.removed"],
      requiredModules: ["notes"],
    },
  ],
  linkedContextProviders: [
    {
      id: "notes.note",
      moduleId: "notes",
      targetType: "note",
      label: "Note",
      description: "Permission-safe note targets for shared Linked Context pickers.",
      provider: "notes.linked-context.notes",
      responseContract: LINKED_CONTEXT_TARGET_RESPONSE_CONTRACT,
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      requiredModules: ["notes"],
    },
  ],
  notificationEvents: [
    {
      id: "note.updated",
      moduleId: "notes",
      label: "Note Updated",
      description: "Notifies note owners and followers when another user updates a non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
      suppressActorSubscriptions: true,
    },
    {
      id: "note.archived",
      moduleId: "notes",
      label: "Note Archived",
      description: "Notifies followers when another user archives a non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
      suppressActorSubscriptions: true,
    },
    {
      id: "note.restored",
      moduleId: "notes",
      label: "Note Restored",
      description: "Notifies followers when another user restores a non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
      suppressActorSubscriptions: true,
    },
    {
      id: "note.linked",
      moduleId: "notes",
      label: "Note Linked",
      description: "Notifies followers when another user adds linked context to a non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
      suppressActorSubscriptions: true,
    },
    {
      id: "note.unlinked",
      moduleId: "notes",
      label: "Note Unlinked",
      description: "Notifies followers when another user removes linked context from a non-secure note.",
      defaultEnabled: true,
      defaultPriority: "normal",
      recipientMode: "explicit_users",
      suppressActorSubscriptions: true,
    },
  ],
  notificationFollowTargets: [
    {
      targetType: "note",
      moduleId: "notes",
      label: "Note",
      description: "Allows a user to follow one note and receive notifications for meaningful non-secure note changes.",
      requiredReadPermission: NOTE_PERMISSIONS.VIEW,
      eventTypes: [
        "note.updated",
        "note.archived",
        "note.restored",
        "note.linked",
        "note.unlinked",
      ],
    },
  ],
  help: {
    sections: [
      {
        id: "notes.overview",
        moduleId: "notes",
        title: "Notes",
        description: "Current Notes behavior for usage, Library buckets, collections, Linked Context, Markdown, revisions, secure notes, and files.",
        sortOrder: 120,
        audience: "user",
        tags: ["notes", "library"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
    ],
    articles: [
      {
        id: "notes.basics",
        slug: "notes-basics",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Using Notes",
        summary: "Create internal working notes and keep them organized without leaving the current workspace.",
        contentPath: "modules/notes/using-notes.md",
        sortOrder: 10,
        audience: "user",
        tags: ["notes", "basics"],
        relatedArticleIds: ["notes.library", "notes.collections", "notes.linking"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.library",
        slug: "notes-library",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes Library",
        summary: "Use the Notes Library to filter notes by current purpose and archived state.",
        contentPath: "modules/notes/notes-library.md",
        sortOrder: 20,
        audience: "user",
        tags: ["notes", "library", "archive"],
        relatedArticleIds: ["notes.active-work", "notes.ongoing-areas", "notes.reference-library", "notes.archive"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.collections",
        slug: "notes-collections",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes Collections",
        summary: "Use collections as single-bucket folders for notes, not as permissions or record links.",
        contentPath: "modules/notes/notes-collections.md",
        sortOrder: 30,
        audience: "user",
        tags: ["notes", "collections", "library"],
        relatedArticleIds: ["notes.library", "notes.archive"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.active-work",
        slug: "notes-active-work",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Active Work",
        summary: "Keep notes for work in progress in Active Work.",
        contentPath: "modules/notes/active-work.md",
        sortOrder: 40,
        audience: "user",
        tags: ["notes", "active work", "library"],
        relatedArticleIds: ["notes.library", "notes.linking"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.ongoing-areas",
        slug: "notes-ongoing-areas",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Ongoing Areas",
        summary: "Keep durable responsibilities and recurring context in Ongoing Areas.",
        contentPath: "modules/notes/ongoing-areas.md",
        sortOrder: 50,
        audience: "user",
        tags: ["notes", "ongoing areas", "library"],
        relatedArticleIds: ["notes.library", "notes.linking"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.reference-library",
        slug: "notes-reference-library",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Reference Library",
        summary: "Keep retained notes and supporting material in Reference Library.",
        contentPath: "modules/notes/reference-library.md",
        sortOrder: 60,
        audience: "user",
        tags: ["notes", "reference library", "library"],
        relatedArticleIds: ["notes.library", "notes.collections"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.archive",
        slug: "notes-archive",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Archive",
        summary: "Move completed notes to Archive while preserving their original Library bucket.",
        contentPath: "modules/notes/archive.md",
        sortOrder: 70,
        audience: "user",
        tags: ["notes", "archive", "library"],
        relatedArticleIds: ["notes.library", "notes.revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.markdown",
        slug: "notes-markdown",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Markdown",
        summary: "Write note bodies in safe Markdown.",
        contentPath: "modules/notes/markdown.md",
        sortOrder: 80,
        audience: "user",
        tags: ["notes", "markdown"],
        relatedArticleIds: ["notes.linking", "notes.revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.linking",
        slug: "notes-linking",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Note Linking",
        summary: "Connect notes to the records they describe without changing access rules.",
        contentPath: "modules/notes/note-linking.md",
        sortOrder: 90,
        audience: "user",
        tags: ["notes", "links"],
        relatedArticleIds: ["notes.basics", "notes.active-work", "notes.ongoing-areas"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.revisions",
        slug: "notes-revisions",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Note Revisions",
        summary: "Review meaningful note changes and restore earlier versions when allowed.",
        contentPath: "modules/notes/note-revisions.md",
        sortOrder: 100,
        audience: "user",
        tags: ["notes", "revisions", "history"],
        relatedArticleIds: ["notes.archive", "notes.secure-notes"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW_HISTORY],
      },
      {
        id: "notes.secure-notes",
        slug: "notes-secure-notes",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Secure Notes",
        summary: "Use secure notes for encrypted-at-rest body content with stricter access rules.",
        contentPath: "modules/notes/secure-notes.md",
        sortOrder: 110,
        audience: "user",
        tags: ["notes", "secure notes"],
        relatedArticleIds: ["notes.basics", "notes.revisions"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
      {
        id: "notes.attachments-search",
        slug: "notes-attachments-search",
        sectionId: "notes.overview",
        moduleId: "notes",
        title: "Notes, Files, and Search",
        summary: "Attach files to notes and find non-secure notes through workspace search.",
        contentPath: "modules/notes/notes-files-and-search.md",
        sortOrder: 120,
        audience: "user",
        tags: ["notes", "files", "search"],
        relatedArticleIds: ["notes.library", "notes.secure-notes"],
        requiredModules: ["notes"],
        requiredPermissions: [NOTE_PERMISSIONS.VIEW],
      },
    ],
  },
  frameworkDependencies: [
    "module-access",
    "permissions-service",
    "workspace-settings",
  ],
  moduleDependencies: [],
  workspaceCapabilityRequirements: [],
};

export { notesModule };
