import { NOTE_PERMISSIONS } from "./access-policy.js";

const notesHelp = {
  help: {
      sections: [
        {
          id: "notes.overview",
          moduleId: "notes",
          title: "Notes",
          description: "Current Notes behavior for usage, Library buckets, collections, Linked Context, Markdown, revisions, secure notes, and files.",
          sortOrder: 120,
          audience: "user",
          tags: ["notes", "library"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
      ],
      articles: [
        {
          id: "notes.basics",
          slug: "notes-basics",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Using Notes",
          summary: "Create internal working notes and keep them organized without leaving the current workspace.",
          contentPath: "modules/notes/using-notes.md",
          sortOrder: 10,
          audience: "user",
          tags: ["notes", "basics"],
          relatedArticleIds: ["notes.library", "notes.collections", "notes.linking"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.library",
          slug: "notes-library",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Notes Library",
          summary: "Use the Notes Library to filter notes by current purpose and archived state.",
          contentPath: "modules/notes/notes-library.md",
          sortOrder: 20,
          audience: "user",
          tags: ["notes", "library", "archive"],
          relatedArticleIds: ["notes.active-work", "notes.ongoing-areas", "notes.reference-library", "notes.archive"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.collections",
          slug: "notes-collections",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Notes Collections",
          summary: "Use collections as single-bucket folders for notes, not as permissions or record links.",
          contentPath: "modules/notes/notes-collections.md",
          sortOrder: 30,
          audience: "user",
          tags: ["notes", "collections", "library"],
          relatedArticleIds: ["notes.library", "notes.archive"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.active-work",
          slug: "notes-active-work",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Active Work",
          summary: "Keep notes for work in progress in Active Work.",
          contentPath: "modules/notes/active-work.md",
          sortOrder: 40,
          audience: "user",
          tags: ["notes", "active work", "library"],
          relatedArticleIds: ["notes.library", "notes.linking"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.ongoing-areas",
          slug: "notes-ongoing-areas",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Ongoing Areas",
          summary: "Keep durable responsibilities and recurring context in Ongoing Areas.",
          contentPath: "modules/notes/ongoing-areas.md",
          sortOrder: 50,
          audience: "user",
          tags: ["notes", "ongoing areas", "library"],
          relatedArticleIds: ["notes.library", "notes.linking"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.reference-library",
          slug: "notes-reference-library",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Reference Library",
          summary: "Keep retained notes and supporting material in Reference Library.",
          contentPath: "modules/notes/reference-library.md",
          sortOrder: 60,
          audience: "user",
          tags: ["notes", "reference library", "library"],
          relatedArticleIds: ["notes.library", "notes.collections"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.archive",
          slug: "notes-archive",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Archive",
          summary: "Move completed notes to Archive while preserving their original Library bucket.",
          contentPath: "modules/notes/archive.md",
          sortOrder: 70,
          audience: "user",
          tags: ["notes", "archive", "library"],
          relatedArticleIds: ["notes.library", "notes.revisions"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.markdown",
          slug: "notes-markdown",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Markdown",
          summary: "Write note bodies in safe Markdown.",
          contentPath: "modules/notes/markdown.md",
          sortOrder: 80,
          audience: "user",
          tags: ["notes", "markdown"],
          relatedArticleIds: ["notes.linking", "notes.revisions"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.linking",
          slug: "notes-linking",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Note Linking",
          summary: "Connect notes to the records they describe without changing access rules.",
          contentPath: "modules/notes/note-linking.md",
          sortOrder: 90,
          audience: "user",
          tags: ["notes", "links"],
          relatedArticleIds: ["notes.basics", "notes.active-work", "notes.ongoing-areas"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.revisions",
          slug: "notes-revisions",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Note Revisions",
          summary: "Review meaningful note changes and restore earlier versions when allowed.",
          contentPath: "modules/notes/note-revisions.md",
          sortOrder: 100,
          audience: "user",
          tags: ["notes", "revisions", "history"],
          relatedArticleIds: ["notes.archive", "notes.secure-notes"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW_HISTORY],
        },
        {
          id: "notes.secure-notes",
          slug: "notes-secure-notes",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Secure Notes",
          summary: "Use secure notes for encrypted-at-rest body content with stricter access rules.",
          contentPath: "modules/notes/secure-notes.md",
          sortOrder: 110,
          audience: "user",
          tags: ["notes", "secure notes"],
          relatedArticleIds: ["notes.basics", "notes.revisions"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
        {
          id: "notes.attachments-search",
          slug: "notes-attachments-search",
          sectionId: "notes.overview",
          moduleId: "notes",
          title: "Notes, Files, and Search",
          summary: "Attach files to notes and find non-secure notes through workspace search.",
          contentPath: "modules/notes/notes-files-and-search.md",
          sortOrder: 120,
          audience: "user",
          tags: ["notes", "files", "search"],
          relatedArticleIds: ["notes.library", "notes.secure-notes"],
          requiredModules: ["notes"],
          requiredPermissions: [NOTE_PERMISSIONS.VIEW],
        },
      ],
    },
};

export { notesHelp };
